
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label1;
	private global::Gtk.Entry entryInitialPrice;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label2;
	private global::Gtk.Entry entryExercisePrice;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label3;
	private global::Gtk.Entry entryUpperBound;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label4;
	private global::Gtk.Entry entryLowerBound;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label5;
	private global::Gtk.Entry entryInterestRate;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label6;
	private global::Gtk.Entry entryTimePeriod;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label7;
	private global::Gtk.Entry entrySimulationRuns;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.Button buttonStart;
	private global::Gtk.Alignment alignment2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textviewOutput;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.WidthRequest = 100;
		this.label1.Name = "label1";
		this.label1.Xalign = 1F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Initial Price");
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entryInitialPrice = new global::Gtk.Entry ();
		this.entryInitialPrice.CanFocus = true;
		this.entryInitialPrice.Name = "entryInitialPrice";
		this.entryInitialPrice.IsEditable = true;
		this.entryInitialPrice.InvisibleChar = '•';
		this.hbox1.Add (this.entryInitialPrice);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryInitialPrice]));
		w2.Position = 1;
		this.vbox4.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.WidthRequest = 100;
		this.label2.Name = "label2";
		this.label2.Xalign = 1F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Exercise Price");
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entryExercisePrice = new global::Gtk.Entry ();
		this.entryExercisePrice.CanFocus = true;
		this.entryExercisePrice.Name = "entryExercisePrice";
		this.entryExercisePrice.IsEditable = true;
		this.entryExercisePrice.InvisibleChar = '•';
		this.hbox2.Add (this.entryExercisePrice);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryExercisePrice]));
		w5.Position = 1;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.WidthRequest = 100;
		this.label3.Name = "label3";
		this.label3.Xalign = 1F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Upper Bound");
		this.hbox3.Add (this.label3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entryUpperBound = new global::Gtk.Entry ();
		this.entryUpperBound.CanFocus = true;
		this.entryUpperBound.Name = "entryUpperBound";
		this.entryUpperBound.IsEditable = true;
		this.entryUpperBound.InvisibleChar = '•';
		this.hbox3.Add (this.entryUpperBound);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entryUpperBound]));
		w8.Position = 1;
		this.vbox4.Add (this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.WidthRequest = 100;
		this.label4.Name = "label4";
		this.label4.Xalign = 1F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Lower Bound");
		this.hbox4.Add (this.label4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entryLowerBound = new global::Gtk.Entry ();
		this.entryLowerBound.CanFocus = true;
		this.entryLowerBound.Name = "entryLowerBound";
		this.entryLowerBound.IsEditable = true;
		this.entryLowerBound.InvisibleChar = '•';
		this.hbox4.Add (this.entryLowerBound);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryLowerBound]));
		w12.Position = 1;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.WidthRequest = 100;
		this.label5.Name = "label5";
		this.label5.Xalign = 1F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Interest Rate");
		this.hbox5.Add (this.label5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entryInterestRate = new global::Gtk.Entry ();
		this.entryInterestRate.CanFocus = true;
		this.entryInterestRate.Name = "entryInterestRate";
		this.entryInterestRate.IsEditable = true;
		this.entryInterestRate.InvisibleChar = '•';
		this.hbox5.Add (this.entryInterestRate);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryInterestRate]));
		w15.Position = 1;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.WidthRequest = 100;
		this.label6.Name = "label6";
		this.label6.Xalign = 1F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Time Period");
		this.hbox6.Add (this.label6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.entryTimePeriod = new global::Gtk.Entry ();
		this.entryTimePeriod.CanFocus = true;
		this.entryTimePeriod.Name = "entryTimePeriod";
		this.entryTimePeriod.IsEditable = true;
		this.entryTimePeriod.InvisibleChar = '•';
		this.hbox6.Add (this.entryTimePeriod);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entryTimePeriod]));
		w18.Position = 1;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.WidthRequest = 100;
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulation Runs");
		this.hbox7.Add (this.label7);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label7]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.entrySimulationRuns = new global::Gtk.Entry ();
		this.entrySimulationRuns.CanFocus = true;
		this.entrySimulationRuns.Name = "entrySimulationRuns";
		this.entrySimulationRuns.IsEditable = true;
		this.entrySimulationRuns.InvisibleChar = '•';
		this.hbox7.Add (this.entrySimulationRuns);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entrySimulationRuns]));
		w22.Position = 1;
		this.vbox2.Add (this.hbox7);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.hbox8.Add (this.alignment1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment1]));
		w24.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.buttonStart = new global::Gtk.Button ();
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox8.Add (this.buttonStart);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonStart]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.hbox8.Add (this.alignment2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment2]));
		w26.Position = 2;
		this.vbox2.Add (this.hbox8);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewOutput = new global::Gtk.TextView ();
		this.textviewOutput.WidthRequest = 400;
		this.textviewOutput.HeightRequest = 400;
		this.textviewOutput.CanFocus = true;
		this.textviewOutput.Name = "textviewOutput";
		this.GtkScrolledWindow.Add (this.textviewOutput);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w29.Position = 2;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w30.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 402;
		this.DefaultHeight = 668;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.entryInitialPrice.Changed += new global::System.EventHandler (this.OnEntryInitialPriceChanged);
		this.entryExercisePrice.Changed += new global::System.EventHandler (this.OnEntryExercisePriceChanged);
		this.entryUpperBound.Changed += new global::System.EventHandler (this.OnEntryUpperBoundChanged);
		this.entryLowerBound.Changed += new global::System.EventHandler (this.OnEntryLowerBoundChanged);
		this.entryInterestRate.Changed += new global::System.EventHandler (this.OnEntryInterestRateChanged);
		this.entryTimePeriod.Changed += new global::System.EventHandler (this.OnEntryTimePeriodChanged);
		this.entrySimulationRuns.Changed += new global::System.EventHandler (this.OnEntrySimulationRunsChanged);
		this.buttonStart.Clicked += new global::System.EventHandler (this.OnButtonStartClicked);
	}
}
