#!/bin/bash

mainopt ()
{
    options=("VaryThreads" "VaryChunks" "VaryFiletypes" "Quit")
    select opt in "${options[@]}"
    do
		case $opt in
			"VaryThreads")
				threads
				;;
			"VaryChunks")
				chunks
				;;
			"VaryFiletypes")
				filetypes
				;;
			"Quit")
				break
				;;
			*) echo invalid option;;
	   esac
   done
}


function threads
{
	echo "Running timing on different numbers of threads"
	echo -e "NumberThreads\tReal\tUser\tSys"
    command time -f "            1\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 1 12 > /dev/null
	command time -f "            2\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 2 12 > /dev/null
	command time -f "            3\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 3 12 > /dev/null
	command time -f "            4\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 4 12 > /dev/null
	command time -f "            5\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 5 12 > /dev/null
	command time -f "            6\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 6 12 > /dev/null
	command time -f "            7\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 7 12 > /dev/null
	command time -f "            8\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 8 12 > /dev/null
	command time -f "            9\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 9 12 > /dev/null
	command time -f "           10\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 10 12 > /dev/null
	command time -f "           11\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 11 12 > /dev/null
	command time -f "           12\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 12 12 > /dev/null
	command time -f "           13\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 13 12 > /dev/null
	command time -f "           14\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 14 12 > /dev/null
	command time -f "           15\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 15 12 > /dev/null
	command time -f "           16\t%E\t%U\t%S"  ./orderSearcher diver.raw 4096 16 12 > /dev/null
}

function chunks
{
	echo -e "Running timing on different chunk sizes"
	echo -e
	echo -e "Chunksizes are powers of 2"
	echo -e "ChunkSize\tReal\tUser\tSys"
	command time -f "        8\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       16\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       32\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       64\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      128\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      256\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      512\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     1024\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     2048\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     4096\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     8192\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    16384\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    32768\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    65536\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	echo -e
	echo -e "Chunksizes are NOT powers of 2"
	echo -e "ChunkSize\tReal\tUser\tSys"
	command time -f "        7\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "        9\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       15\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       17\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       31\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       33\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       63\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "       65\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      127\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      129\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      255\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      257\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      511\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "      513\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     1023\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     1025\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     2047\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     2049\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     4095\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     4097\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     8191\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "     8193\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    16383\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    16385\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    32767\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    32769\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    65535\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
	command time -f "    65537\t%E\t%U\t%S"  ./orderSearcher diver.raw 8192 7 12 > /dev/null
}

function filetypes
{
	echo -e
	echo -e "##################################################################"
	echo -e "Examining a RAW file"
	echo -e "##################################################################"
	echo -e 
	./orderSearcher diver.raw 32 5 20 
	echo -e "##################################################################"
	echo -e "Examining a JPG file"
	echo -e "##################################################################"
	echo -e 
	./orderSearcher diver.jpg 32 5 20
	echo -e "##################################################################"
	echo -e "Examining a BMP file"
	echo -e "##################################################################"
	echo -e 
	./orderSearcher diver.bmp 32 5 20
	echo -e "##################################################################"
	echo -e "Examining a GIF file"
	echo -e "##################################################################"
	echo -e 
	./orderSearcher diver.gif 32 5 20
	echo -e "##################################################################"
	echo -e "Examining a no zeros file"
	echo -e "##################################################################"
	echo -e 
	./orderSearcher diver.nz 32 5 20
}

mainopt	 
