#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "bert.cs.uic.edu";
$SERVER_PORT = 15214;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
