Dialog Class Reference
The Dialog class Main UI class.
#include <dialog.h>
Signals
void playerChanged ()
Public Member Functions
Dialog ()
Dialog::Dialog Constructor.
~Dialog ()
Dialog::~Dialog Destructor.
void setupGame ()
Dialog::setupGame Sets up the game.
void setupDialog ()
Dialog::setupDialog Sets up the dialog.
Private Types
enum { NumButtons = 7
 }
Private Slots
void on_newGame_selected ()
Dialog::on_newGame_selected Sets up a new game.
void on_playerChanged ()
Dialog::on_playerChanged Slot for when the player is changed.
Private Member Functions
void createMenu ()
Dialog::createMenu Creates the menu.
void setupPlayers (int)
Dialog::setupPlayers Sets up the players.
void createHorizontalGroupBox ()
Dialog::createHorizontalGroupBox Creates the rack and buttons.
void createGridGroupBox ()
Dialog::createGridGroupBox Creates the playing board.
void createFormGroupBox ()
void createLabelGroupBox ()
Dialog::createLabelGroupBox Creates the labels that represent the players.
void loadDictionary ()
Dialog::loadDictionary Loads the dictionary.
Private Attributes
QMenuBar * menuBar
QGroupBox * horizontalGroupBox
QGroupBox * gridGroupBox
QGroupBox * labelGroupBox
QPushButton * cancel
QPushButton * play
QPushButton * pass
QMenu * fileMenu
QAction * newGameAction
QAction * exitAction
Board * board
Rack * rack
Game * game
Dictionary * dictionary
vector< Player * > players
short int player_cnt
Detailed Description
The Dialog class Main UI class.
Definition at line 20 of file dialog.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator
NumButtons
Definition at line 30 of file dialog.h.
{ NumButtons = 7 };
Constructor & Destructor Documentation
Dialog::Dialog ()
Dialog::Dialog Constructor.
Definition at line 12 of file dialog.cpp.
References board, Board::getBoard(), Rack::getRack(), loadDictionary(), rack, setupDialog(), setupGame(), and setupPlayers().
{
    loadDictionary();
    setupPlayers(2);
    board = Board::getBoard();
    rack = Rack::getRack();
    setupGame();
    connect(board, SIGNAL(invalidMove()), rack, SLOT(on_invalidMove()));
    setupDialog();
}
Dialog::~Dialog ()
Dialog::~Dialog Destructor.
Definition at line 28 of file dialog.cpp.
References dictionary, game, and players.
                {
    while(!players.empty()){
        delete players.back();
        players.pop_back();
    }
    delete game;
    delete dictionary;
}
Member Function Documentation
void Dialog::createFormGroupBox () [private]
void Dialog::createGridGroupBox () [private]
Dialog::createGridGroupBox Creates the playing board.
Definition at line 188 of file dialog.cpp.
References board, gridGroupBox, and Board::spaces.
Referenced by setupDialog().
{
    gridGroupBox = new QGroupBox();
    QGridLayout *layout = new QGridLayout;
    layout->setContentsMargins(0,0,0,0);
    layout->setSpacing(0);
    for (int i = 0; i < 15; i++) {
        for (int j = 0; j < 15; j++) {
            layout->addWidget(board->spaces[i][j], i, j);
        }
    }
    gridGroupBox->setLayout(layout);
}
void Dialog::createHorizontalGroupBox () [private]
Dialog::createHorizontalGroupBox Creates the rack and buttons.
Definition at line 122 of file dialog.cpp.
References cancel, Board::getBoard(), Rack::getRack(), Rack::getSpace(), horizontalGroupBox, pass, play, rack, and RACKSIZE.
Referenced by setupDialog().
{
    horizontalGroupBox = new QGroupBox(tr("Player"));
    QHBoxLayout *layout = new QHBoxLayout;
    layout->setContentsMargins(10,10,3,3);
    layout->setSpacing(0);
    for (int i = 0; i < RACKSIZE; ++i) {
        layout->addWidget(rack->getSpace(i));
    }
    layout->insertStretch(7);
    play = new QPushButton(tr("Play"));
    layout->addWidget(play);
    pass = new QPushButton(tr("Pass"));
    layout->addWidget(pass);
    cancel = new QPushButton(tr("Cancel"));
    layout->addWidget(cancel);
    horizontalGroupBox->setLayout(layout);
    connect(play, SIGNAL(clicked()), Board::getBoard(), SLOT(on_playButton_clicked()));
    connect(pass, SIGNAL(clicked()), Board::getBoard(), SLOT(on_passButton_clicked()));
    connect(cancel, SIGNAL(clicked()), Board::getBoard(), SLOT(on_cancelButton_clicked
      ()));
    connect(cancel, SIGNAL(clicked()), Rack::getRack(), SLOT(on_cancelButton_clicked()))
      ;
}
void Dialog::createLabelGroupBox () [private]
Dialog::createLabelGroupBox Creates the labels that represent the players.
Definition at line 152 of file dialog.cpp.
References labelGroupBox, on_playerChanged(), playerChanged(), players, PlayerLabel::setActive(), and PlayerLabel::setInactive().
Referenced by setupDialog().
{
    labelGroupBox = new QGroupBox();
    QGridLayout *layout = new QGridLayout;
    layout->setContentsMargins(0,0,0,0);
    layout->setSpacing(0);
    Player* player;
    // create the labels and connect them for each player
    for(unsigned int i = 0; i < 4; i++) {
        if (i < players.size()){
             cout << "setting player" << endl;
            player = players[i];
        }
        else {
            cout << "setting player to null" << endl;
            player = NULL;
        }
        PlayerLabel *label = new PlayerLabel(player);
        if (i == 0){
            label->setActive();
        }
        else {
            label->setInactive();
        }
        connect(this, SIGNAL(playerChanged()), label, SLOT(
      on_playerChanged()));
        layout->addWidget(label, i / 2, i % 2);
    }
    labelGroupBox->setLayout(layout);
}
void Dialog::createMenu () [private]
Dialog::createMenu Creates the menu.
Definition at line 105 of file dialog.cpp.
References exitAction, fileMenu, menuBar, newGameAction, and on_newGame_selected().
Referenced by setupDialog().
{
    menuBar = new QMenuBar;
    fileMenu = new QMenu(tr("&File"), this);
    newGameAction = fileMenu->addAction(tr("&New Game"));
    exitAction = fileMenu->addAction(tr("E&xit"));
    menuBar->addMenu(fileMenu);
    connect(newGameAction, SIGNAL(triggered()), this, SLOT(
      on_newGame_selected()));
    connect(exitAction, SIGNAL(triggered()), this, SLOT(accept()));
}
void Dialog::loadDictionary () [private]
Dialog::loadDictionary Loads the dictionary.
Definition at line 95 of file dialog.cpp.
References dictionary, and DictionaryLoader::load().
Referenced by Dialog().
                           {
    dictionary = new Dictionary();
    DictionaryLoader *dictionaryLoader = new DictionaryLoader(
      dictionary, ":/resources/dictionary.txt");
    dictionaryLoader->load();
    delete dictionaryLoader;
}
void Dialog::on_newGame_selected () [private], [slot]
Dialog::on_newGame_selected Sets up a new game.
Definition at line 205 of file dialog.cpp.
References board, game, players, Board::reset(), and setupGame().
Referenced by createMenu().
{
    if (game != NULL){
        delete(game);
        game = NULL;
    }
    for (unsigned int i = 0; i < players.size(); i++){
        players.at(i)->clearScore();
    }
    board->reset();
    setupGame();
}
void Dialog::on_playerChanged () [private], [slot]
Dialog::on_playerChanged Slot for when the player is changed.
Definition at line 222 of file dialog.cpp.
References playerChanged().
Referenced by createLabelGroupBox(), and setupGame().
{
    cout << "Dialog is emitting an on_playerChanged() signal." << endl;
    emit (playerChanged());
}
void Dialog::playerChanged () [signal]
Referenced by createLabelGroupBox(), on_playerChanged(), and setupGame().
void Dialog::setupDialog ()
Dialog::setupDialog Sets up the dialog.
Todo
Todo this is not great, but the only way I could disable resizing on Linux
Definition at line 52 of file dialog.cpp.
References createGridGroupBox(), createHorizontalGroupBox(), createLabelGroupBox(), createMenu(), gridGroupBox, horizontalGroupBox, labelGroupBox, and menuBar.
Referenced by Dialog().
{
    createMenu();
    createHorizontalGroupBox();
    createGridGroupBox();
    createLabelGroupBox();
    QVBoxLayout *mainLayout = new QVBoxLayout;
    mainLayout->setMenuBar(menuBar);
    mainLayout->addWidget(gridGroupBox);
    mainLayout->addWidget(horizontalGroupBox);
    mainLayout->addWidget(labelGroupBox);
    setLayout(mainLayout);
    setWindowTitle(tr("Words for CS 340 Students"));
    setFixedSize(580, 700);
}
void Dialog::setupGame ()
Dialog::setupGame Sets up the game.
Definition at line 40 of file dialog.cpp.
References board, dictionary, game, on_playerChanged(), playerChanged(), players, rack, Rack::refresh(), and Board::setGame().
Referenced by Dialog(), and on_newGame_selected().
{
    game = new Game(players, dictionary);
    board->setGame(game);
    rack->refresh(game);
    connect(game, SIGNAL(playerChanged()), this, SLOT(
      on_playerChanged()));
    emit(playerChanged());
}
void Dialog::setupPlayers (int num) [private]
Dialog::setupPlayers Sets up the players.
Parameters
num The number of players to set up
Definition at line 77 of file dialog.cpp.
References AIPlayer::AIPlayer(), and players.
Referenced by Dialog().
{
    for (int i = 0; i < num; i++){
        QString *playerName = new QString("Player " + QString::number(i + 1));
        if (i == 0){
            players.push_back(new HumanPlayer(*playerName));
        }
        else {
            // players.push_back(new HumanPlayer(*playerName));
            players.push_back(new AIPlayer(*playerName));
        }
        cout << players.back()->getName().toStdString();
    };
}
Member Data Documentation
Board* Dialog::board [private]
The Board
Definition at line 45 of file dialog.h.
Referenced by createGridGroupBox(), Dialog(), on_newGame_selected(), and setupGame().
QPushButton* Dialog::cancel [private]
The cancel button
Definition at line 37 of file dialog.h.
Referenced by createHorizontalGroupBox().
Dictionary* Dialog::dictionary [private]
The Dictionary
Definition at line 48 of file dialog.h.
Referenced by loadDictionary(), setupGame(), and ~Dialog().
QAction* Dialog::exitAction [private]
Action when the user chooses to exit
Definition at line 43 of file dialog.h.
Referenced by createMenu().
QMenu* Dialog::fileMenu [private]
The file menu
Definition at line 41 of file dialog.h.
Referenced by createMenu().
Game* Dialog::game [private]
The Game
Definition at line 47 of file dialog.h.
Referenced by on_newGame_selected(), setupGame(), and ~Dialog().
QGroupBox* Dialog::gridGroupBox [private]
A grid group box
Definition at line 34 of file dialog.h.
Referenced by createGridGroupBox(), and setupDialog().
QGroupBox* Dialog::horizontalGroupBox [private]
A horizontal group box
Definition at line 33 of file dialog.h.
Referenced by createHorizontalGroupBox(), and setupDialog().
QGroupBox* Dialog::labelGroupBox [private]
A label group box
Definition at line 35 of file dialog.h.
Referenced by createLabelGroupBox(), and setupDialog().
QMenuBar* Dialog::menuBar [private]
The menu bar
Definition at line 32 of file dialog.h.
Referenced by createMenu(), and setupDialog().
QAction* Dialog::newGameAction [private]
Action when the user chooses a new game
Definition at line 42 of file dialog.h.
Referenced by createMenu().
QPushButton* Dialog::pass [private]
The pass button
Definition at line 39 of file dialog.h.
Referenced by createHorizontalGroupBox().
QPushButton* Dialog::play [private]
The play button
Definition at line 38 of file dialog.h.
Referenced by createHorizontalGroupBox().
short int Dialog::player_cnt [private]
The number of Players
Definition at line 50 of file dialog.h.
vector<Player*> Dialog::players [private]
The Players
Definition at line 49 of file dialog.h.
Referenced by createLabelGroupBox(), on_newGame_selected(), setupGame(), setupPlayers(), and ~Dialog().
Rack* Dialog::rack [private]
The Rack
Definition at line 46 of file dialog.h.
Referenced by createHorizontalGroupBox(), Dialog(), and setupGame().
The documentation for this class was generated from the following files:
Scrabble/dialog.h
Scrabble/dialog.cpp