Move Class Reference
The Move class Contains a single move from a Rack to the Board.
#include <move.h>
Public Member Functions
Move (Player *, Letter *, int, int, int)
Move::Move Constructor.
Player * getPlayer ()
Move::getPlayer Getter for player.
Letter * getLetter ()
Move::getLetter Getter for Letter.
int getX ()
Move::getX Getter for boardX.
int getY ()
Move::getY Getter for bordY.
int getRackPosition ()
Move::getRackPosition Gets the position this letter draws from, from the rack.
Move * apply ()
Move::apply Applies to the board.
Move * unapply ()
Move::unapply Unapplies from the board.
Move * finalize ()
Move::finalize Finalizes the board.
Private Attributes
Player * player
Letter * letter
int rackPosition
int boardX
int boardY
Detailed Description
The Move class Contains a single move from a Rack to the Board.
Definition at line 12 of file move.h.
Constructor & Destructor Documentation
Move::Move (Player * player, Letter * letter, int rackPosition, int boardX, int boardY)
Move::Move Constructor.
Parameters
player The player
letter The letter
rackPosition The position in the rack
boardX The x position on the board
boardY The y position on the board
Definition at line 11 of file move.cpp.
References boardX, boardY, letter, player, and rackPosition.
                                                                                  {
    this->player = player;
    this->letter = letter;
    this->rackPosition = rackPosition;
    this->boardX = boardX;
    this->boardY = boardY;
}
Member Function Documentation
Move * Move::apply ()
Move::apply Applies to the board.
Returns
this
Definition at line 68 of file move.cpp.
References boardX, boardY, Board::getBoard(), Space::getLetter(), Rack::getRack(), Rack::getSpace(), Space::isInactive(), rackPosition, Space::setLetter(), Space::setNew(), Space::setPlaced(), and Board::spaces.
Referenced by Board::moveLetterToBoard().
{
    Space *boardSpace = Board::getBoard()->spaces[
      boardX][boardY];
    if(boardSpace->isInactive()){
        Space *rackSpace = Rack::getRack()->getSpace(
      rackPosition);
        boardSpace->setLetter(rackSpace->getLetter());
        rackSpace->setPlaced();
        boardSpace->setNew();
    }
    return this;
}
Move * Move::finalize ()
Move::finalize Finalizes the board.
Returns
this
Definition at line 100 of file move.cpp.
References boardX, boardY, Board::getBoard(), Space::setOnBoard(), and Board::spaces.
{
    Board::getBoard()->spaces[boardX][boardY]->
      setOnBoard();
    return this;
}
Letter * Move::getLetter ()
Move::getLetter Getter for Letter.
Returns
letter
Definition at line 59 of file move.cpp.
References letter.
Referenced by Play::clearLetter(), Play::getCharArray(), and AIPlayer::play().
{
    return letter;
}
Player * Move::getPlayer ()
Move::getPlayer Getter for player.
Returns
player
Definition at line 50 of file move.cpp.
References player.
{
    return player;
}
int Move::getRackPosition ()
Move::getRackPosition Gets the position this letter draws from, from the rack.
Returns
rackposition.
Definition at line 41 of file move.cpp.
References rackPosition.
Referenced by AIPlayer::play().
{
    return rackPosition;
}
int Move::getX ()
Move::getX Getter for boardX.
Returns
boardX
Definition at line 23 of file move.cpp.
References boardX.
Referenced by AIPlayer::play(), and Play::validate().
{
    return boardX;
}
int Move::getY ()
Move::getY Getter for bordY.
Returns
boardY
Definition at line 32 of file move.cpp.
References boardY.
Referenced by AIPlayer::play(), and Play::validate().
{
    return boardY;
}
Move * Move::unapply ()
Move::unapply Unapplies from the board.
Returns
this
Definition at line 84 of file move.cpp.
References boardX, boardY, Board::getBoard(), Rack::getRack(), Rack::getSpace(), Space::isInactive(), rackPosition, Space::setInactive(), Space::setLetter(), and Board::spaces.
{
    Space *boardSpace = Board::getBoard()->spaces[
      boardX][boardY];
    if(!boardSpace->isInactive()){
        Space *rackSpace = Rack::getRack()->getSpace(
      rackPosition);
        boardSpace->setLetter(NULL);
        rackSpace->setInactive();
        boardSpace->setInactive();
    }
    return this;
}
Member Data Documentation
int Move::boardX [private]
The x position on the board
Definition at line 31 of file move.h.
Referenced by apply(), finalize(), getX(), Move(), and unapply().
int Move::boardY [private]
The y position on the board
Definition at line 32 of file move.h.
Referenced by apply(), finalize(), getY(), Move(), and unapply().
Letter* Move::letter [private]
The Letter
Definition at line 29 of file move.h.
Referenced by getLetter(), and Move().
Player* Move::player [private]
The Player who made the move
Definition at line 28 of file move.h.
Referenced by getPlayer(), and Move().
int Move::rackPosition [private]
The position on the rack it came from
Definition at line 30 of file move.h.
Referenced by apply(), getRackPosition(), Move(), and unapply().
The documentation for this class was generated from the following files:
Scrabble/move.h
Scrabble/move.cpp