Player Class Reference
The Player class Abstract class representing a Player.
#include <player.h>
Public Member Functions
Player (QString)
Player::Player Constructor.
virtual ~Player ()
Player::~Player Deconstructor.
virtual bool isHumanPlayer ()
Player::isHumanPlayer.
virtual bool isAIPlayer ()
Player::isAIPlayer.
Player * removeLetter (Letter *)
Player::removeLetter Removes the first letter that matches.
Player * clearLetters ()
Player::clearLetters Clears the player's letters.
Player * getNewLetters (LetterPool *)
Player::getNewLetters Fills the letters after a play.
QString * getLettersAsQstring ()
Player::getLettersAsQstring Gets the letters held as a string.
Letter * getLetter (int)
Player::getLetter Getter for letter.
void fillLetters (LetterPool *)
Player::Requests for his letters to be filled out.
int getLetterCount ()
Player::getLetterCount.
size_t addLetter (Letter *letter)
Player::addLetter Adds a letter to a players set of letters.
QString getName ()
Player::getName Getter for name.
int addScore (int)
Player::addScore Adds to a player's score.
void clearScore ()
Player::clearScore Clears the Player's score.
int getScore ()
Player::getScore Gets a player's score.
Protected Attributes
QString name
vector< Letter * > letters
unsigned int score
Friends
ostream & operator<< (ostream &os, const Player &player)
operator << Overloaded operator for Player&
Detailed Description
The Player class Abstract class representing a Player.
Definition at line 19 of file player.h.
Constructor & Destructor Documentation
Player::Player (QString name)
Player::Player Constructor.
Parameters
name
Definition at line 8 of file player.cpp.
References letters, name, and score.
{
    this->name = name;
    this->score = 0;
    this->letters.reserve(7);
}
Player::~Player () [virtual]
Player::~Player Deconstructor.
Definition at line 18 of file player.cpp.
{
}
Member Function Documentation
size_t Player::addLetter (Letter * letter)
Player::addLetter Adds a letter to a players set of letters.
Parameters
letter The letter to add
Returns
On sucess a positive integer of the number of tiles held, on failure -1
Definition at line 55 of file player.cpp.
References letters, and MAXTILESINHAND.
                                       {
    if (letters.size() < (MAXTILESINHAND - 1)){
        letters.push_back(letter);
        return letters.size();
    }
    return -1;
}
int Player::addScore (int newScore)
Player::addScore Adds to a player's score.
Parameters
newScore The amount to add
Returns
The modified score
Definition at line 136 of file player.cpp.
References score.
Referenced by Game::nextTurn().
                                 {
    this->score += newScore;
    return this->score;
}
Player * Player::clearLetters ()
Player::clearLetters Clears the player's letters.
Returns
this
Definition at line 174 of file player.cpp.
References letters.
                            {
    while(!letters.empty()){
        delete letters.back();
        letters.pop_back();
    }
    return this;
}
void Player::clearScore ()
Player::clearScore Clears the Player's score.
Definition at line 145 of file player.cpp.
References score.
{
    this->score = 0;
}
void Player::fillLetters (LetterPool * pool)
Player::Requests for his letters to be filled out.
Definition at line 162 of file player.cpp.
References LetterPool::getRandomLetter(), LetterPool::isEmpty(), letters, and MAXTILESINHAND.
Referenced by getNewLetters().
                                        {
    while(!pool->isEmpty() && letters.size() < MAXTILESINHAND)
    {
           letters.push_back(pool->getRandomLetter());
    }
}
Letter * Player::getLetter (int i)
Player::getLetter Getter for letter.
Parameters
i The index of the letter
Returns
A pointer to the letter or NULL if it doesn't exist
Definition at line 111 of file player.cpp.
References letters.
Referenced by Rack::refresh().
                              {
    if (i >= 0 && (unsigned int)i < letters.size()){
        return letters.at(i);
    }
    return NULL;
}
int Player::getLetterCount ()
Player::getLetterCount.
Returns
Returns the number of letter in players hand for debugging purposes mostly
Definition at line 28 of file player.cpp.
References letters.
                          {
    return (int)letters.size();
}
QString * Player::getLettersAsQstring ()
Player::getLettersAsQstring Gets the letters held as a string.
Returns
A QString representing the letters held
Definition at line 122 of file player.cpp.
References letters.
                                    {
    size_t numLetters = letters.size();
    QString *qstring = new QString;
    for(size_t i = 0; i < numLetters; i++){
        qstring->push_back(*(letters[i]->asQCharPtr()));
    }
    return qstring;
}
QString Player::getName ()
Player::getName Getter for name.
Returns
name
Definition at line 100 of file player.cpp.
References name.
Referenced by PlayerLabel::updateText().
{
    return name;
}
Player * Player::getNewLetters (LetterPool * pool)
Player::getNewLetters Fills the letters after a play.
Parameters
pool The letter pool
Returns
this
Todo
Todo this is a bug , it removes the first letter regardless
Definition at line 84 of file player.cpp.
References fillLetters(), Rack::getRack(), letters, and RACKSIZE.
Referenced by Game::nextTurn().
{
    for(int i = RACKSIZE - 1; i >= 0; i--){
        if (Rack::getRack()->getSpace(i)->isPlaced()){
            letters.erase(letters.begin() + i);
        }
    }
    fillLetters(pool);
    return this;
}
int Player::getScore ()
Player::getScore Gets a player's score.
Returns
The player's score
Definition at line 154 of file player.cpp.
References score.
Referenced by PlayerLabel::updateText().
                     {
    return this->score;
}
bool Player::isAIPlayer () [virtual]
Player::isAIPlayer.
Returns
True if an AI player, false otherwise
Reimplemented in AIPlayer.
Definition at line 45 of file player.cpp.
                       {
    return false;
}
bool Player::isHumanPlayer () [virtual]
Player::isHumanPlayer.
Returns
True if a human player, false otherwise
Reimplemented in HumanPlayer.
Definition at line 36 of file player.cpp.
{
    return false;
}
Player * Player::removeLetter (Letter * letter)
Player::removeLetter Removes the first letter that matches.
Parameters
letter The letter to remove
Returns
A pointer to the letter object, or NULL if not found
Definition at line 69 of file player.cpp.
References letters.
                                           {
    size_t numLetters = letters.size();
    for(size_t i = 0; i < numLetters; i++){
        if (letters[i] == letter){
            letters.erase(letters.begin() + i);
        }
    }
    return this;
}
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const Player & player) [friend]
operator << Overloaded operator for Player&
Parameters
os The ostream
player The player
Returns
The modified ostream
Definition at line 188 of file player.cpp.
                                                       {
    for(unsigned int i = 0; i < player.letters.size(); i++) {
        os << *(player.letters[i]);
    }
    return os;
}
Member Data Documentation
vector<Letter*> Player::letters [protected]
The Letters the Player has
Definition at line 23 of file player.h.
Referenced by addLetter(), clearLetters(), fillLetters(), getLetter(), getLetterCount(), getLettersAsQstring(), getNewLetters(), operator<<(), AIPlayer::play(), Player(), removeLetter(), and HumanPlayer::~HumanPlayer().
QString Player::name [protected]
The Player's name
Definition at line 22 of file player.h.
Referenced by getName(), and Player().
unsigned int Player::score [protected]
The Player's score
Definition at line 24 of file player.h.
Referenced by addScore(), clearScore(), getScore(), and Player().
The documentation for this class was generated from the following files:
Scrabble/player.h
Scrabble/player.cpp