Rack Class Reference
The Rack class Singleton class representing the current player on the Dialog.
#include <rack.h>
Public Slots
void on_cancelButton_clicked ()
Rack::on_cancelButton_clicked Handles the cancelButton_clicked events.
void on_invalidMove ()
Rack::on_invalidMove Handles invalideMove events.
Public Member Functions
~Rack ()
Rack::~Rack Destructor.
Rack * setSpace (int, Space *)
Rack::setSpace Setter for a space.
Space * getSpace (int)
Rack::getSpace Gets the space at an index.
Rack * refresh (Game *)
Rack::refresh Refreshes the rack to show the rack of the current player.
bool isActive ()
Rack::isActive Is the space active.
void inactivateByLetter (Letter *)
Rack::inactivateByLetter Inactivates a space by the letter is points to.
Rack * deleteLetter (Letter *)
Rack::deleteLetter Deletes a letter from the rack.
Rack * inactivateOtherSpaces (int)
Rack::inactivateOtherSpaces Inactivates other spaces in the rack.
int getActiveIndex ()
Rack::getActiveIndex Gets the index of the currently active space.
int getPos (Letter *L)
Rack::getPos Gets the position of the Rack based on the letter address provided.
Static Public Member Functions
static Rack * getRack ()
Rack::getRack Gets the rack or creates a new one.
Private Member Functions
Rack (QObject *parent=0)
Rack::Rack Constructor.
Private Attributes
Space * spaces [RACKSIZE]
Static Private Attributes
static bool isSet = false
static Rack * rack = NULL
Detailed Description
The Rack class Singleton class representing the current player on the Dialog.
Definition at line 16 of file rack.h.
Constructor & Destructor Documentation
Rack::~Rack ()
Rack::~Rack Destructor.
Definition at line 35 of file rack.cpp.
References RACKSIZE, and spaces.
{
    for (int i = 0; i < RACKSIZE; i++){
        delete(spaces[i]);
    }
}
Rack::Rack (QObject * parent = 0) [explicit], [private]
Rack::Rack Constructor.
Parameters
parent The parent
Definition at line 10 of file rack.cpp.
References RACKSIZE, and spaces.
Referenced by getRack().
                          :
    QObject(parent)
{
    for (int i = 0; i < RACKSIZE; i++){
        spaces[i] = new Space(i);
    }
}
Member Function Documentation
Rack * Rack::deleteLetter (Letter * letter)
Rack::deleteLetter Deletes a letter from the rack.
Parameters
letter The letter to conpare to the rack
Returns
this
Definition at line 157 of file rack.cpp.
References Space::clear(), RACKSIZE, and spaces.
Referenced by Board::~Board().
{
    for (int i = 0; i < RACKSIZE; i++){
        if (spaces[i]->getLetter() == letter){
            spaces[i]->clear();
        }
    }
    return this;
}
int Rack::getActiveIndex ()
Rack::getActiveIndex Gets the index of the currently active space.
Returns
the index
Definition at line 118 of file rack.cpp.
References isActive(), RACKSIZE, and spaces.
{
    for(int i = 0; i < RACKSIZE; i++){
        if (spaces[i]->isActive()){
            return i;
        }
    }
    return -1;
}
int Rack::getPos (Letter * L)
Rack::getPos Gets the position of the Rack based on the letter address provided.
Parameters
L The letter.
Returns
the integer position on the rack. -1 if it doesn't exist.
Definition at line 143 of file rack.cpp.
References spaces.
{
    for(int i = 0; i < 7; i++)
        if(this->spaces[i]->getLetter() == L)
            return i;
    return -1;
}
Rack * Rack::getRack () [static]
Rack::getRack Gets the rack or creates a new one.
Returns
The rack
Definition at line 22 of file rack.cpp.
References isSet, rack, and Rack().
Referenced by AIPlayer::_assist_ai_search(), Move::apply(), Dialog::createHorizontalGroupBox(), Dialog::Dialog(), Player::getNewLetters(), Board::moveLetterToBoard(), Game::nextTurn(), Space::on_clicked(), AIPlayer::play(), Move::unapply(), and Board::~Board().
{
    if(isSet){
        return rack;
    }
    isSet = true;
    rack = new Rack();
    return rack;
}
Space * Rack::getSpace (int i)
Rack::getSpace Gets the space at an index.
Parameters
i The index
Returns
The space at i
Definition at line 133 of file rack.cpp.
References spaces.
Referenced by Move::apply(), Dialog::createHorizontalGroupBox(), and Move::unapply().
{
    return spaces[i];
}
void Rack::inactivateByLetter (Letter * letter)
Rack::inactivateByLetter Inactivates a space by the letter is points to.
Parameters
letter The letter used to compare
Definition at line 75 of file rack.cpp.
References RACKSIZE, Space::setInactive(), and spaces.
Referenced by Space::on_clicked(), and AIPlayer::play().
{
    for (int i = 0; i < RACKSIZE; i++){
        if (spaces[i]->getLetter() == letter){
            spaces[i]->setInactive();
        }
    }
}
Rack * Rack::inactivateOtherSpaces (int x)
Rack::inactivateOtherSpaces Inactivates other spaces in the rack.
Parameters
x The position not to inactivate
Returns
this
Definition at line 60 of file rack.cpp.
References isActive(), RACKSIZE, Space::setInactive(), and spaces.
Referenced by Space::on_clicked().
{
    for (int i = 0; i < RACKSIZE; i++){
        if (x != i && spaces[i]->isActive()){
            spaces[i]->setInactive();
        }
    }
    return this;
}
bool Rack::isActive ()
Rack::isActive Is the space active.
Returns
true if active
Definition at line 103 of file rack.cpp.
References RACKSIZE, and spaces.
Referenced by getActiveIndex(), and inactivateOtherSpaces().
{
    for(int i = 0; i < RACKSIZE; i++){
        if (spaces[i]->isActive()){
            return true;
        }
    }
    return false;
}
void Rack::on_cancelButton_clicked () [slot]
Rack::on_cancelButton_clicked Handles the cancelButton_clicked events.
Definition at line 171 of file rack.cpp.
References RACKSIZE, Space::setInactive(), and spaces.
{
    for (int i = 0; i < RACKSIZE; i++){
        if (spaces[i]->isPlaced()) {
            spaces[i]->setInactive();
        }
    }
}
void Rack::on_invalidMove () [slot]
Rack::on_invalidMove Handles invalideMove events.
Definition at line 183 of file rack.cpp.
References RACKSIZE, Space::setInactive(), and spaces.
{
    for (int i = 0; i < RACKSIZE; i++){
        if (spaces[i]->isPlaced()) {
            spaces[i]->setInactive();
        }
    }
}
Rack * Rack::refresh (Game * game)
Rack::refresh Refreshes the rack to show the rack of the current player.
Parameters
game The game
Returns
this
Definition at line 90 of file rack.cpp.
References Space::clear(), Game::currentPlayer(), Player::getLetter(), RACKSIZE, Space::setLetter(), and spaces.
Referenced by Game::nextTurn(), and Dialog::setupGame().
{
    for (int i = 0; i < RACKSIZE; i++){
        spaces[i]->clear();
        spaces[i]->setLetter(game->currentPlayer()->
      getLetter(i));
    }
    return this;
}
Rack * Rack::setSpace (int i, Space * space)
Rack::setSpace Setter for a space.
Parameters
i The position to set
space The space to set
Returns
this
Definition at line 48 of file rack.cpp.
References spaces.
{
    spaces[i] = space;
    return this;
}
Member Data Documentation
bool Rack::isSet = false [static], [private]
Flag if the Rack has been set
Definition at line 35 of file rack.h.
Referenced by getRack().
Rack * Rack::rack = NULL [static], [private]
The Rack
Definition at line 36 of file rack.h.
Referenced by getRack().
Space* Rack::spaces[RACKSIZE] [private]
The container for the Spaces
Definition at line 37 of file rack.h.
Referenced by deleteLetter(), getActiveIndex(), getPos(), getSpace(), inactivateByLetter(), inactivateOtherSpaces(), isActive(), on_cancelButton_clicked(), on_invalidMove(), Rack(), refresh(), setSpace(), and ~Rack().
The documentation for this class was generated from the following files:
Scrabble/rack.h
Scrabble/rack.cpp