Game Class Reference
The Game class Encapsulates a game.
#include <game.h>
Signals
void playerChanged ()
Public Member Functions
Game (vector< Player * >, Dictionary *)
Game::Game Constructor for up to a 4-player game.
~Game ()
Game::~Game Destructor.
Game * setup ()
Player * currentPlayer ()
Game::currentPlayer Gets the current player.
Play * currentPlay ()
Game::currentPlay Gets the curret play.
bool nextTurn ()
Game::nextTurn Finalizes the current turn. If a player is an APlayer, play() is called.
Game * getNewLetters ()
Public Attributes
Dictionary * dictionary
Private Attributes
int turn
LetterPool * pool
vector< Player * > players
vector< Play * > plays
int numPlayers
Friends
ostream & operator<< (ostream &os, const Game &game)
operator << Overloading the << operator for debugging information
Detailed Description
The Game class Encapsulates a game.
Definition at line 20 of file game.h.
Constructor & Destructor Documentation
Game::Game (vector< Player * > players, Dictionary * dictionary)
Game::Game Constructor for up to a 4-player game.
Parameters
players The players we are constructive this game for.
dictionary The dictionary to use
Definition at line 10 of file game.cpp.
References currentPlayer(), dictionary, nextTurn(), numPlayers, playerChanged(), players, plays, pool, and turn.
                                                         {
    this->turn = 0;
    this->pool = new LetterPool;
    this->numPlayers = players.size();
    this->players = players;
    this->plays.push_back(new Play());
    this->dictionary = dictionary;
    for(std::vector<Player*>::iterator it = players.begin(); it !=
      players.end(); ++it) {
        (*it)->fillLetters(pool);
        assert((*it)->getLetterCount() == 7);
    }
    emit(playerChanged());
    if(currentPlayer()->isAIPlayer()){
        ((AIPlayer*)currentPlayer())->play(*dictionary, &
      plays.back());
        nextTurn();
    }
}
Game::~Game ()
Game::~Game Destructor.
Definition at line 57 of file game.cpp.
References players.
           {
    for(std::vector<Player*>::iterator it = players.begin(); it !=
      players.end(); ++it) {
        if (*it != NULL){
            (*it)->clearLetters();
            assert((*it)->getLetterCount() == 0);
        }
    }
}
Member Function Documentation
Play * Game::currentPlay ()
Game::currentPlay Gets the curret play.
Returns
A pointer to the current play
Definition at line 79 of file game.cpp.
References plays.
Referenced by Board::moveLetterToBoard(), nextTurn(), Board::on_cancelButton_clicked(), and Space::on_clicked().
{
    return plays.back();
}
Player * Game::currentPlayer ()
Game::currentPlayer Gets the current player.
Returns
A pointer to the current player
Definition at line 70 of file game.cpp.
References numPlayers, players, and turn.
Referenced by Game(), Board::moveLetterToBoard(), nextTurn(), and Rack::refresh().
{
    return players[turn % numPlayers];
}
Game* Game::getNewLetters ()
bool Game::nextTurn ()
Game::nextTurn Finalizes the current turn. If a player is an APlayer, play() is called.
Returns
this
Definition at line 35 of file game.cpp.
References Player::addScore(), currentPlay(), currentPlayer(), dictionary, Play::finalizeMoves(), Board::getBoard(), Player::getNewLetters(), Rack::getRack(), playerChanged(), plays, pool, Rack::refresh(), and turn.
Referenced by Game(), Board::on_passButton_clicked(), and Board::on_playButton_clicked().
{
    currentPlayer()->addScore(Board::getBoard()->score(
      plays.back()));
    currentPlayer()->getNewLetters(pool);
    currentPlay()->finalizeMoves();
    turn = turn + 1;
    Rack::getRack()->refresh(this);
    emit(playerChanged());
    plays.push_back(new Play());
    if(currentPlayer()->isAIPlayer() && currentPlayer()->getLetterCount() > 0){
        ((AIPlayer*)currentPlayer())->play(*dictionary, &
      plays.back());
        nextTurn();
    }
    return true;
}
void Game::playerChanged () [signal]
Referenced by Game(), and nextTurn().
Game* Game::setup ()
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const Game & game) [friend]
operator << Overloading the << operator for debugging information
Parameters
os The output stream
game The game object
Returns
The modified output stream
Definition at line 90 of file game.cpp.
                                                   {
    os << "This is a " << game.numPlayers << " player game." << endl;
    os << *(Board::getBoard());
    return os;
}
Member Data Documentation
Dictionary* Game::dictionary
The Dictionary
Definition at line 31 of file game.h.
Referenced by Game(), nextTurn(), Board::validateWordHorizontal(), and Board::validateWordVertical().
int Game::numPlayers [private]
The number of players
Definition at line 28 of file game.h.
Referenced by currentPlayer(), Game(), and operator<<().
vector<Player*> Game::players [private]
The container for the Players
Definition at line 26 of file game.h.
Referenced by currentPlayer(), Game(), and ~Game().
vector<Play*> Game::plays [private]
The container for the Plays
Definition at line 27 of file game.h.
Referenced by currentPlay(), Game(), and nextTurn().
LetterPool* Game::pool [private]
The pool of letters
Definition at line 25 of file game.h.
Referenced by Game(), and nextTurn().
int Game::turn [private]
The number of the turn
Definition at line 24 of file game.h.
Referenced by currentPlayer(), Game(), and nextTurn().
The documentation for this class was generated from the following files:
Scrabble/game.h
Scrabble/game.cpp