LetterPool Class Reference
The LetterPool class Holds the letters not already in play.
#include <letterpool.h>
Public Member Functions
LetterPool ()
LetterPool Constructor.
~LetterPool ()
LetterPool Destructor.
Letter * getRandomLetter ()
LetterPool::getRandomLetter() returns a random letter from the pool, removing it from the pool.
bool isEmpty ()
LetterPool::isEmpty, checks if the letter pool has letters left.
Private Member Functions
Letter * removeFromPool (int)
Letter::removeFromPool, removes a single letter from the letter vector.
bool addLetters (char, int)
LetterPool::addLetters() adds characters to the letter pool.
Private Attributes
QVector< Letter * > letter_vector
Detailed Description
The LetterPool class Holds the letters not already in play.
Definition at line 14 of file letterpool.h.
Constructor & Destructor Documentation
LetterPool::LetterPool ()
LetterPool Constructor.
Definition at line 7 of file letterpool.cpp.
References addLetters(), and letter_vector.
{
    srand (time(NULL));
    addLetters('a',9);
    addLetters('b',2);
    addLetters('c',2);
    addLetters('d',4);
    addLetters('e',12);
    addLetters('f',2);
    addLetters('g',3);
    addLetters('h',2);
    addLetters('i',9);
    addLetters('j',1);
    addLetters('k',1);
    addLetters('l',4);
    addLetters('m',2);
    addLetters('n',6);
    addLetters('o',8);
    addLetters('p',2);
    addLetters('q',1);
    addLetters('r',6);
    addLetters('s',4);
    addLetters('t',6);
    addLetters('u',4);
    addLetters('v',2);
    addLetters('w',2);
    addLetters('x',1);
    addLetters('y',2);
    addLetters('z',1);
    addLetters(' ',2);
    if (letter_vector.size() != 100){
        cout << "Invalid Letter Pool Construction. Letter count: "
             << letter_vector.size() << endl;
    }
}
LetterPool::~LetterPool ()
LetterPool Destructor.
Definition at line 48 of file letterpool.cpp.
References letter_vector.
{
    while(!letter_vector.empty()){
        delete letter_vector.back();
        letter_vector.pop_back();
    }
}
Member Function Documentation
bool LetterPool::addLetters (char letter, int count) [private]
LetterPool::addLetters() adds characters to the letter pool.
Parameters
letter what letter to add
count The count of letters to add
Returns
True if addition was succesful
Definition at line 71 of file letterpool.cpp.
References letter_vector.
Referenced by LetterPool().
{
    Letter *temp;
    for(int i = 0; i < count; i++){
        temp = new Letter(letter);
        letter_vector.push_back(temp);
    }
    return true;
}
Letter * LetterPool::getRandomLetter ()
LetterPool::getRandomLetter() returns a random letter from the pool, removing it from the pool.
Returns
Letter* to the random letter
Definition at line 87 of file letterpool.cpp.
References letter_vector, and removeFromPool().
Referenced by Player::fillLetters().
{
    return removeFromPool(rand() % letter_vector.size());
}
bool LetterPool::isEmpty ()
LetterPool::isEmpty, checks if the letter pool has letters left.
Returns
True if the letter pool is empty
Definition at line 60 of file letterpool.cpp.
References letter_vector.
Referenced by Player::fillLetters().
{
    return letter_vector.isEmpty();
}
Letter * LetterPool::removeFromPool (int i) [private]
Letter::removeFromPool, removes a single letter from the letter vector.
Parameters
i Index of the letter to be removed
Returns
Letter* to the removed letter
Definition at line 97 of file letterpool.cpp.
References letter_vector.
Referenced by getRandomLetter().
{
    Letter* temp = letter_vector[i];
    letter_vector.remove(i);
    return temp;
}
Member Data Documentation
QVector<Letter*> LetterPool::letter_vector [private]
The holder for the Letters
Definition at line 18 of file letterpool.h.
Referenced by addLetters(), getRandomLetter(), isEmpty(), LetterPool(), removeFromPool(), and ~LetterPool().
The documentation for this class was generated from the following files:
Scrabble/letterpool.h
Scrabble/letterpool.cpp