Play Class Reference
The Play class Wrapper for a set of Moves that make up a Play.
#include <play.h>
Public Member Functions
Play (QList< Move * > *, Player *)
Play::Play Constructor.
Play ()
Play class constructor.
Play (const Play &other)
Play::Play Copy Constructor.
~Play ()
Play destructor.
bool isEmpty ()
Play::isEmpty, checks whether the move vector has any elements.
bool validate (Dictionary &dict)
Play::validate will return whether or not this is a valid play on the board.
Play * addMove (Player *, Move *)
Play::addMove, adds a single move to the list of plays.
Play * applyMoves ()
Play::applyMoves temporarily applies each move of the play to the board.
Play * unapplyMoves ()
Play::unapplyMoves does the opposite of the temporary placement, and inactivates the spaces.
Play * finalizeMoves ()
Play::finalizeMoves Permanently adds each move of the play to the board.
Play * clearMoves ()
Play::clearMoves removes all elements from the play list.
Play * clearLetter (Letter *)
Play::clearLetter Clears a move by the Letter* it contains.
int size ()
Play::size, checks the number of moves in a play.
class Player * getPlayer ()
Play::getPlayer.
int getValue ()
Play::getValue, checks the value of the current play.
QString getCharArray ()
Play::getCharArray gets the Play's moves in the form of a string.
Private Member Functions
bool validate_right (int x_start, int y, Dictionary &dict, Board *myboard)
Play::validate_right Validates a Play to the right.
bool validate_down (int y_start, int x, Dictionary &dict, Board *myboard)
Play::validate_down Validates a Play downward.
Private Attributes
QList< Move * > * moves
Player * player
int value
Friends
class AIPlayer
Detailed Description
The Play class Wrapper for a set of Moves that make up a Play.
Definition at line 16 of file play.h.
Constructor & Destructor Documentation
Play::Play (QList< Move * > * moves, Player * player)
Play::Play Constructor.
Parameters
moves A list of moves
player The player
Definition at line 18 of file play.cpp.
References player, and value.
{
    this->moves = new QList<Move*>();
    this->value = 0;
    for(int i = 0; i < moves->size(); i++) {
        this->moves->insert(i,new Move(*moves->at(i)));
        this->value += this->moves->at(i)->getLetter()->getValue();
    }
    // this->moves = moves;
    this->player = player;
}
Play::Play ()
Play class constructor.
Definition at line 6 of file play.cpp.
References moves, player, and value.
{
    this->moves = new QList<Move*>();
    this->value = 0;
    this->player = 0;
}
Play::Play (const Play & other)
Play::Play Copy Constructor.
Parameters
other Other Play
Definition at line 239 of file play.cpp.
References moves, player, and value.
                            {
    this->player = other.player;
    this->value = other.value;
    this->moves = new QList<Move*>();
    int i = 0;
    for(QList<Move*>::ConstIterator it = other.moves->cbegin(); it != other.
      moves->cend(); it++)
    {
        Move * curmove = *it;
        this->moves->insert(i,curmove);
        i++;
    }
}
Play::~Play ()
Play destructor.
Definition at line 33 of file play.cpp.
References clearMoves().
{
    clearMoves();
}
Member Function Documentation
Play * Play::addMove (Player * player, Move * move)
Play::addMove, adds a single move to the list of plays.
Parameters
player reference to the player that made the move
move reference to the object of type Move
Returns
this
Definition at line 73 of file play.cpp.
References moves, and player.
Referenced by Board::moveLetterToBoard().
                                             {
    this->player = player;
    moves->push_back(move);
    return this;
}
Play * Play::applyMoves ()
Play::applyMoves temporarily applies each move of the play to the board.
Definition at line 96 of file play.cpp.
References moves.
{
    for (int i = 0; i < moves->size(); i++){
        moves->at(i)->unapply();
    }
    return this;
}
Play * Play::clearLetter (Letter * letter)
Play::clearLetter Clears a move by the Letter* it contains.
Parameters
letter The letter to find by
Returns
this
Definition at line 55 of file play.cpp.
References Move::getLetter(), and moves.
Referenced by Space::on_clicked(), and AIPlayer::play().
{
   for (int i = 0; i < moves->size(); i++){
        Move *move = moves->at(i);
        if (letter == move->getLetter()){
            moves->removeAt(i);
        }
    }
    return this;
}
Play * Play::clearMoves ()
Play::clearMoves removes all elements from the play list.
Definition at line 41 of file play.cpp.
References moves.
Referenced by Board::on_cancelButton_clicked(), and ~Play().
{
    while (!moves->empty()){
        delete (moves->back());
        moves->pop_back();
    }
    return this;
}
Play * Play::finalizeMoves ()
Play::finalizeMoves Permanently adds each move of the play to the board.
Definition at line 83 of file play.cpp.
References moves.
Referenced by Game::nextTurn().
{
    for (int i = 0; i < moves->size(); i++){
        moves->at(i)->finalize();
    }
    return this;
}
QString Play::getCharArray ()
Play::getCharArray gets the Play's moves in the form of a string.
Returns
a QString representing this play's moves.
Definition at line 265 of file play.cpp.
References Letter::asQCharPtr(), Move::getLetter(), and moves.
{
    QString result = "";
    for(QList<Move*>::Iterator moveit = moves->begin(); moveit != moves->end(); moveit++)
    {
        Move * curmove = *moveit;
        result += curmove->getLetter()->asQCharPtr()->toLatin1();
    }
    return result;
}
const Player * Play::getPlayer ()
Play::getPlayer.
Returns
Player* of the player making a play
Definition at line 280 of file play.cpp.
References player.
{
    return player;
}
int Play::getValue ()
Play::getValue, checks the value of the current play.
Returns
int with the value of the play
Definition at line 256 of file play.cpp.
References value.
Referenced by _pred_value_sort().
{
    return value;
}
bool Play::isEmpty ()
Play::isEmpty, checks whether the move vector has any elements.
Returns
true if the move vector is empty
Definition at line 123 of file play.cpp.
References moves.
Referenced by validate().
                  {
    return moves->isEmpty();
}
int Play::size ()
Play::size, checks the number of moves in a play.
Returns
number of elements in a move vector
Definition at line 131 of file play.cpp.
References moves.
Referenced by Board::score().
{
    return moves->size();
}
Play * Play::unapplyMoves ()
Play::unapplyMoves does the opposite of the temporary placement, and inactivates the spaces.
Definition at line 109 of file play.cpp.
References moves.
{
    for (int i = 0; i < moves->size(); i++){
        moves->at(i)->getX();
        moves->at(i)->getY();
    }
    return this;
}
bool Play::validate (Dictionary & dict)
Play::validate will return whether or not this is a valid play on the board.
Returns
true or false
Definition at line 175 of file play.cpp.
References Board::getBoard(), Move::getX(), Move::getY(), Space::isBlank(), isEmpty(), moves, Board::spaces, validate_down(), and validate_right().
{
    // We assume moves are unique!
    Board * myboard = Board::getBoard();
    bool xmove = true;
    bool ymove = true;
    if(this->isEmpty())
        return false;
    int anchorposx = moves->at(0)->getX();
    int anchorposy = moves->at(0)->getY();
    int lowx = anchorposx;
    int lowy = anchorposy;
    int highx = anchorposx;
    int highy = anchorposy;
    for(QList<Move*>::Iterator it = (moves->begin()+1); it < moves->end(); it++)
    {
        // It want to move it move it...
        Move * move = *it;
        if(myboard->spaces[move->getX()][move->getY()]->isBlank() == false)
            return false;
        xmove = (move->getX() == anchorposx);
        ymove = (move->getY() == anchorposy);
        // If you didn't move along either x or y, you're doing it wrong.
        // If you did move along both x _and_ y, you're doing it wrong as well.
        if(xmove == ymove)
            return false;
        if(move->getX() > highx)
            highx = move->getX();
        if(move->getX() < lowx)
            lowx = move->getX();
        if(move->getY() > highy)
            highy = move->getY();
        if(move->getY() < lowy)
            lowy = move->getY();
    }
    // Now, first we check wether or not the word in the direction we put the tiles, is a word.
    // Doing it this way makes it easier to do sideways checks.
    if(xmove) {
        validate_right(highx, highy, dict, myboard);
        for(int x = lowx; x < highx; x++)
            validate_down(x,highy,dict,myboard);
    }
    if(ymove) {
        validate_down(highy, highx, dict, myboard);
        for(int y = lowy; y < highy; y++)
            validate_right(highx,y,dict,myboard);
    }
    return true;
}
bool Play::validate_down (int y_start, int x, Dictionary & dict, Board * myboard) [private]
Play::validate_down Validates a Play downward.
Parameters
y_start The start of the y position
x The x position
dict The dictionary
myboard The board
Returns
Definition at line 162 of file play.cpp.
References Letter::asQCharPtr(), Space::getLetter(), Space::isBlank(), Dictionary::isWord(), and Board::spaces.
Referenced by validate().
{
    QString downcheck = "";
    for(int firstposy=y_start ; firstposy >= 0 && !myboard->spaces[x][firstposy]->
      isBlank(); firstposy--) {
        downcheck += *(myboard->spaces[x][firstposy]->getLetter()->
      asQCharPtr());
    }
    return dict.isWord(downcheck);
}
bool Play::validate_right (int x_start, int y, Dictionary & dict, Board * myboard) [private]
Play::validate_right Validates a Play to the right.
Parameters
x_start The start of the x position
y The y position
dict The dictionary
myboard The board
Returns
Definition at line 144 of file play.cpp.
References Letter::asQCharPtr(), Space::getLetter(), Space::isBlank(), Dictionary::isWord(), and Board::spaces.
Referenced by validate().
{
    QString rightcheck = "";
    for(int firstposx=x_start ; firstposx >= 0 && !myboard->spaces[firstposx][y]->
      isBlank(); firstposx--) {
        rightcheck += *(myboard->spaces[firstposx][y]->getLetter()->
      asQCharPtr());
    }
    return dict.isWord(rightcheck);
}
Friends And Related Function Documentation
friend class AIPlayer [friend]
Definition at line 46 of file play.h.
Member Data Documentation
QList<Move*>* Play::moves [private]
Container for the moves
Definition at line 19 of file play.h.
Referenced by addMove(), applyMoves(), clearLetter(), clearMoves(), finalizeMoves(), getCharArray(), isEmpty(), AIPlayer::play(), Play(), size(), unapplyMoves(), and validate().
Player* Play::player [private]
The Player that made the moves
Definition at line 20 of file play.h.
Referenced by addMove(), getPlayer(), and Play().
int Play::value [private]
The value of the play
Definition at line 21 of file play.h.
Referenced by getValue(), and Play().
The documentation for this class was generated from the following files:
Scrabble/play.h
Scrabble/play.cpp