DictionaryLoader Class Reference
The DictionaryLoader class Loads a file of words into the dictionary.
#include <dictionaryloader.h>
Public Member Functions
DictionaryLoader (Dictionary *, QString)
DictionaryLoader::DictionaryLoader Constructor for dictionary loader.
DictionaryLoader * load ()
DictionaryLoader::load Loads the dictionary.
Private Attributes
QString fileName
Dictionary * dictionary
Detailed Description
The DictionaryLoader class Loads a file of words into the dictionary.
Definition at line 9 of file dictionaryloader.h.
Constructor & Destructor Documentation
DictionaryLoader::DictionaryLoader (Dictionary * dictionary, QString fileName)
DictionaryLoader::DictionaryLoader Constructor for dictionary loader.
Definition at line 9 of file dictionaryloader.cpp.
References dictionary, and fileName.
                                                                          {
    this->dictionary = dictionary;
    this->fileName = fileName;
}
Member Function Documentation
DictionaryLoader * DictionaryLoader::load ()
DictionaryLoader::load Loads the dictionary.
Returns
this
Definition at line 18 of file dictionaryloader.cpp.
References Dictionary::addWord(), dictionary, and fileName.
Referenced by UnitTest::dictionarytest(), and Dialog::loadDictionary().
                                        {
    QFile file(fileName);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)){
        cout << "Could not open dictionary file!" << endl;
        return this;
    }
    QTextStream in(&file);
    QString line = in.readLine();
    while (!line.isNull()) {
        dictionary->addWord(line, false);
        line = in.readLine();
    }
    return this;
}
Member Data Documentation
Dictionary* DictionaryLoader::dictionary [private]
The dictionary to load
Definition at line 13 of file dictionaryloader.h.
Referenced by DictionaryLoader(), and load().
QString DictionaryLoader::fileName [private]
The name of the file holding the dictionary
Definition at line 12 of file dictionaryloader.h.
Referenced by DictionaryLoader(), and load().
The documentation for this class was generated from the following files:
Scrabble/dictionaryloader.h
Scrabble/dictionaryloader.cpp