Dictionary Class Reference
The Dictionary class Encapsulates dicitonary operations.
#include <dictionary.h>
Public Member Functions
Dictionary ()
Dictionary::Dictionary Constructor for dictionary.
~Dictionary ()
Dictionary::~Dictionary Destructor.
bool isWord (QString)
Dictionary::isWord Returns boolean true if is a word.
bool addWord (QString, bool)
Dictionary::addWord Adds a word to the dictionary.
unsigned wordcount ()
Dictionary::wordcount Getter for word count.
Private Attributes
Trie * words
unsigned _wcount
Friends
class UnitTest
class AIPlayer
Detailed Description
The Dictionary class Encapsulates dicitonary operations.
Definition at line 12 of file dictionary.h.
Constructor & Destructor Documentation
Dictionary::Dictionary ()
Dictionary::Dictionary Constructor for dictionary.
Definition at line 8 of file dictionary.cpp.
{
    words = new Trie();
    _wcount = 0;
}
Dictionary::~Dictionary ()
Dictionary::~Dictionary Destructor.
Definition at line 17 of file dictionary.cpp.
{
    delete words;
}
Member Function Documentation
bool Dictionary::addWord (QString word, bool checkWord)
Dictionary::addWord Adds a word to the dictionary.
Parameters
word The word to add
checkWord Set to true if the word should be checked against the database prior to insertion
Returns
true if success, false otherwise
Definition at line 39 of file dictionary.cpp.
Referenced by DictionaryLoader::load().
{
    if (checkWord && words->searchWord(word)){
        return false;
    }
    words->addWord(word);
    _wcount++;
    return true;
}
bool Dictionary::isWord (QString word)
Dictionary::isWord Returns boolean true if is a word.
Parameters
word The word to match
Returns
true if in dictionary, false otherwise
Definition at line 27 of file dictionary.cpp.
Referenced by UnitTest::dictionarytest(), Play::validate_down(), Play::validate_right(), Board::validateWordHorizontal(), and Board::validateWordVertical().
{
    return words->searchWord(word);
}
unsigned Dictionary::wordcount ()
Dictionary::wordcount Getter for word count.
Returns
The word count
Definition at line 53 of file dictionary.cpp.
Referenced by UnitTest::dictionarytest().
{
    return _wcount;
}
Friends And Related Function Documentation
friend class AIPlayer [friend]
Definition at line 19 of file dictionary.h.
friend class UnitTest [friend]
Definition at line 18 of file dictionary.h.
Member Data Documentation
unsigned Dictionary::_wcount [private]
The count of the words
Definition at line 16 of file dictionary.h.
Trie* Dictionary::words [private]
The container for the words
Definition at line 15 of file dictionary.h.
Referenced by AIPlayer::ai_search(), and UnitTest::dictionarytest().
The documentation for this class was generated from the following files:
Scrabble/dictionary.h
Scrabble/dictionary.cpp