Space Class Reference
The Space class A visual representation of a space on the board that may or may not be filled with a Letter.
#include <space.h>
Public Slots
void on_clicked ()
Space::on_clicked Handles on_cicked events.
Public Member Functions
Space (int, int, int, int, QString, QString)
Space::Space Constructor.
Space (int)
Space::Space Default constructor for space object.
~Space ()
Space::~Space Destructor.
Space (const Space &other)
Space::Space Copy constructor.
Space * setLetter (Letter *)
Space::setLetter Setter for letter.
Space * setStartSpace (bool)
Space::setStartSpace Sets a starting space.
Space * clear ()
Space::clearLetter Clears the letter.
Space * setColor (QString color)
Space::setColor Sets the color.
Letter * getLetter ()
Space::getLetter Getter for letter.
QString getColor ()
Space::getColor Getter for color.
int getValue ()
Space::getValue Get the value of the space.
int getLetterMultiplier ()
Space::getLetterMultiplier Getter for letter multiplier.
int getWordMultiplier ()
Space::getWordMultiplier Getter for word multiplier.
int getX ()
Space::getX Getter for x.
int getY ()
Space::getY Getter for y.
bool isStartSpace ()
Space::isStartSpace Is the space the start space.
bool isInactive ()
Space::isInactive Is the space inactive.
bool isActive ()
Space::isActive Is the space active.
bool isNew ()
Space::isNew Is the space new.
bool isPlaced ()
Space::isPlaced Is the space placed.
bool isBlank ()
Space::isBlank Is the space blank.
bool isOnBoard ()
Space::isOnBoard Is the space on the board.
Space * setInactive ()
Space::setInactive Sets the space as inactive.
Space * setActive ()
Space::setActive Sets the space as active.
Space * setNew ()
Space::setNew Sets the space as new.
Space * setPlaced ()
Space::setPlaced Sets the space as placed.
Space * setOnBoard ()
Space::setOnBoard Sets the space as on the board.
Private Member Functions
Space * setupDefaults ()
Space::setupDefaults Sets up default attributes (to be called from Constructor.
Private Attributes
Letter * letter
int letterMultiplier
int wordMultiplier
bool startSpace
QString label
QString color
int x
int y
int state
Friends
class AIPlayer
ostream & operator<< (ostream &os, const Space &space)
operator << Overloads the << operator for debugging information
Detailed Description
The Space class A visual representation of a space on the board that may or may not be filled with a Letter.
Definition at line 28 of file space.h.
Constructor & Destructor Documentation
Space::Space (int x, int y, int letterMultiplier, int wordMultiplier, QString label, QString color)
Space::Space Constructor.
Parameters
x The x position of this space
y The y position of this space
letterMultiplier The letter multiplier
wordMultiplier The word multiplier
label The default label for this space
color The default color for this space
Definition at line 31 of file space.cpp.
References color, label, letterMultiplier, setupDefaults(), wordMultiplier, x, and y.
                                           : QPushButton(NULL)
{
    this->x = x;
    this->y = y;
    this->letterMultiplier = letterMultiplier;
    this->wordMultiplier = wordMultiplier;
    this->label = label;
    this->color = color;
    setStyleSheet("background-color: " + color + "; border-width: 0 px; color : black");
    setText(label);
    setupDefaults();
}
Space::Space (int x)
Space::Space Default constructor for space object.
Definition at line 8 of file space.cpp.
References color, letterMultiplier, setupDefaults(), startSpace, wordMultiplier, x, and y.
{
    this->x = x;
    this->y = -1;
    this->letterMultiplier = 1;
    this->wordMultiplier = 1;
    this->startSpace = false;
    this->color = "white";
    setStyleSheet("background-color: white; border-width: 0 px");
    setText("");
    setupDefaults();
}
Space::~Space ()
Space::~Space Destructor.
Definition at line 67 of file space.cpp.
References letter.
             {
    if (this->letter != NULL){
        delete (this->letter);
    }
}
Space::Space (const Space & other)
Space::Space Copy constructor.
Parameters
other The other space
Definition at line 77 of file space.cpp.
References letter, letterMultiplier, startSpace, and wordMultiplier.
                               : QPushButton(NULL)
{
    this->letter=new Letter(*(other.letter));
    this->letterMultiplier=other.letterMultiplier;
    this->wordMultiplier=other.wordMultiplier;
    this->startSpace=other.startSpace;
}
Member Function Documentation
Space * Space::clear ()
Space::clearLetter Clears the letter.
Returns
A pointer to the cleared letter, or NULL if none was set
Definition at line 140 of file space.cpp.
References color, INACTIVE, label, letter, setColor(), and state.
Referenced by Rack::deleteLetter(), Board::on_cancelButton_clicked(), on_clicked(), AIPlayer::play(), Rack::refresh(), and Board::reset().
                    {
    this->letter = NULL;
    setText(label);
    setColor(color);
    state = INACTIVE;
    return this;
}
QString Space::getColor ()
Space::getColor Getter for color.
Returns
The QString representation of the color
Definition at line 180 of file space.cpp.
References color.
Referenced by Board::getColor().
{
    return color;
}
Letter * Space::getLetter ()
Space::getLetter Getter for letter.
Returns
letter
Definition at line 118 of file space.cpp.
References letter.
Referenced by Move::apply(), Board::scoreHorizontalWord(), Board::scoreVerticalWord(), Board::startCovered(), Play::validate_down(), Play::validate_right(), Board::validateWordHorizontal(), and Board::validateWordVertical().
{
    return this->letter;
}
int Space::getLetterMultiplier ()
Space::getLetterMultiplier Getter for letter multiplier.
Returns
The letter multiplier
Definition at line 152 of file space.cpp.
References letterMultiplier.
Referenced by Board::scoreHorizontalWord(), and Board::scoreVerticalWord().
                               {
    return letterMultiplier;
}
int Space::getValue ()
Space::getValue Get the value of the space.
Returns
The multiplier times the letter value, or -1 if no letter set
Definition at line 127 of file space.cpp.
References Letter::getValue(), letter, and letterMultiplier.
                   {
    if (this->letter != NULL){
        return (letterMultiplier * this->letter->getValue());
    }
    else {
        return -1;
    }
}
int Space::getWordMultiplier ()
Space::getWordMultiplier Getter for word multiplier.
Returns
The word multiplier
Definition at line 160 of file space.cpp.
References wordMultiplier.
Referenced by Board::scoreHorizontalWord(), and Board::scoreVerticalWord().
{
    return wordMultiplier;
}
int Space::getX ()
Space::getX Getter for x.
Returns
x
Definition at line 355 of file space.cpp.
References x.
Referenced by AIPlayer::_assist_ai_search().
               {
    return this->x;
}
int Space::getY ()
Space::getY Getter for y.
Returns
y
Definition at line 363 of file space.cpp.
References y.
Referenced by AIPlayer::_assist_ai_search().
               {
    return this->y;
}
bool Space::isActive ()
Space::isActive Is the space active.
Returns
true if yes, false if not
Definition at line 262 of file space.cpp.
References ACTIVE, and state.
Referenced by on_clicked().
{
    return (this->state == ACTIVE);
}
bool Space::isBlank ()
Space::isBlank Is the space blank.
Returns
true if yes, false if not
Definition at line 298 of file space.cpp.
References letter.
Referenced by AIPlayer::_assist_ai_search(), AIPlayer::_touches_2(), AIPlayer::play(), Board::scoreHorizontalWord(), Board::scoreVerticalWord(), Play::validate(), Play::validate_down(), and Play::validate_right().
{
    return (this->letter == NULL);
}
bool Space::isInactive ()
Space::isInactive Is the space inactive.
Returns
true if yes, false if not
Definition at line 271 of file space.cpp.
References INACTIVE, and state.
Referenced by Move::apply(), and Move::unapply().
{
    return (this->state == INACTIVE);
}
bool Space::isNew ()
Space::isNew Is the space new.
Returns
true if yes, false if not
Definition at line 280 of file space.cpp.
References NEW, and state.
Referenced by Board::scoreHorizontalWord(), and Board::scoreVerticalWord().
{
    return (this->state == NEW);
}
bool Space::isOnBoard ()
Space::isOnBoard Is the space on the board.
Returns
true if yes, false if not
Definition at line 289 of file space.cpp.
References ONBOARD, and state.
{
    return (this->state == ONBOARD);
}
bool Space::isPlaced ()
Space::isPlaced Is the space placed.
Returns
true if yes, false if not
Definition at line 253 of file space.cpp.
References PLACED, and state.
{
    return (this->state == PLACED);
}
bool Space::isStartSpace ()
Space::isStartSpace Is the space the start space.
Returns
true if yes, false if not
Definition at line 244 of file space.cpp.
References startSpace.
{
    return startSpace;
}
void Space::on_clicked () [slot]
Space::on_clicked Handles on_cicked events.
Todo
Todo This method is getting long and messy - we should refactor
Definition at line 307 of file space.cpp.
References ACTIVE, Letter::asQCharPtr(), clear(), Play::clearLetter(), Game::currentPlay(), Board::getBoard(), Board::getGame(), Rack::getRack(), Rack::inactivateByLetter(), Rack::inactivateOtherSpaces(), INACTIVE, isActive(), Letter::isAMatch(), Letter::isWildcard(), letter, Board::moveLetterToBoard(), NEW, setActive(), setInactive(), Letter::setLetter(), setLetter(), state, x, and y.
Referenced by setupDefaults().
{
    if (y == -1) { // This is a rack space
        if (this->state == INACTIVE) {
            Rack::getRack()->inactivateOtherSpaces(
      x);
            setActive();
        }
        else if (this->state == ACTIVE){
            setInactive();
        }
    }
    else { // This is a board space
        if (this->state == INACTIVE && Rack::getRack()->
      isActive()){
            Board::getBoard()->moveLetterToBoard(
      Rack::getRack()->getActiveIndex(), x, y);
        }
        else if (this->state == NEW && letter != NULL) {
            if (letter->isWildcard()){
                if (letter->isAMatch('z')){
                    setInactive();
                    letter->setLetter(' ');
                    Board::getBoard()->getGame()->
      currentPlay()->clearLetter(letter);
                    Rack::getRack()->inactivateByLetter(
      letter);
                    clear();
                }
                else {
                    if (letter->isAMatch(' ')){
                        letter->setLetter('a');
                    }
                    else {
                        letter->setLetter(letter->
      asQCharPtr()->toLatin1() + 1);
                    }
                    setLetter(letter);
                }
            }
            else {
                setInactive();
                Board::getBoard()->getGame()->currentPlay()->
      clearLetter(letter);
                Rack::getRack()->inactivateByLetter(
      letter);
                clear();
            }
        }
    }
}
Space * Space::setActive ()
Space::setActive Sets the space as active.
Returns
this
Definition at line 189 of file space.cpp.
References ACTIVE, ACTIVECOLOR, and state.
Referenced by on_clicked().
{
    setStyleSheet("background-color: " + ACTIVECOLOR + "; border-width: 0 px; color: black");
    this->state = ACTIVE;
    return this;
}
Space * Space::setColor (QString color)
Space::setColor Sets the color.
Parameters
color The color to set
Returns
this
Definition at line 170 of file space.cpp.
Referenced by clear(), and setLetter().
{
    setStyleSheet("background-color: " + color + "; border-width: 0 px; color: black");
    return this;
}
Space * Space::setInactive ()
Space::setInactive Sets the space as inactive.
Returns
this
Definition at line 200 of file space.cpp.
References color, INACTIVE, and state.
Referenced by Rack::inactivateByLetter(), Rack::inactivateOtherSpaces(), Board::inactivateOtherSpaces(), Rack::on_cancelButton_clicked(), on_clicked(), Rack::on_invalidMove(), and Move::unapply().
{
    setStyleSheet("background-color: " + this->color + "; border-width: 0 px; color: black");
    this->state = INACTIVE;
    return this;
}
Space * Space::setLetter (Letter * letter)
Space::setLetter Setter for letter.
Parameters
letter The letter to set
Returns
this
Definition at line 102 of file space.cpp.
References Letter::asQCharPtr(), Letter::getValue(), letter, setColor(), state, UNPLAYABLE, and UNPLAYABLECOLOR.
Referenced by Move::apply(), on_clicked(), Rack::refresh(), Board::setSpace(), and Move::unapply().
                                      {
    this->letter = letter;
    if (letter != NULL){
        this->setText(QString (*(letter->asQCharPtr())).toUpper() + "\n" + QString::number(letter
      ->getValue()));
    }
    else {
        this->state = UNPLAYABLE;
        setColor(UNPLAYABLECOLOR);
    }
    return this;
}
Space * Space::setNew ()
Space::setNew Sets the space as new.
Returns
this
Definition at line 211 of file space.cpp.
References NEW, NEWCOLOR, and state.
Referenced by Move::apply(), and AIPlayer::play().
{
    setStyleSheet("background-color: " + NEWCOLOR + "; border-width: 0 px; color: black");
    this->state = NEW;
    return this;
}
Space * Space::setOnBoard ()
Space::setOnBoard Sets the space as on the board.
Returns
this
Definition at line 233 of file space.cpp.
References ONBOARD, ONBOARDCOLOR, and state.
Referenced by Move::finalize().
{
    setStyleSheet("background-color: " + ONBOARDCOLOR + "; border-width: 0 px; color: black");
    this->state = ONBOARD;
    return this;
}
Space * Space::setPlaced ()
Space::setPlaced Sets the space as placed.
Returns
this
Definition at line 222 of file space.cpp.
References PLACED, PLACEDCOLOR, and state.
Referenced by Move::apply().
{
    setStyleSheet("background-color: " + PLACEDCOLOR + "; border-width: 0 px; color: black");
    this->state = PLACED;
    return this;
}
Space * Space::setStartSpace (bool value)
Space::setStartSpace Sets a starting space.
Parameters
value
Returns
Definition at line 91 of file space.cpp.
References startSpace.
Referenced by Board::setupStart().
{
    this->startSpace = value;
    return this;
}
Space * Space::setupDefaults () [private]
Space::setupDefaults Sets up default attributes (to be called from Constructor.
Returns
this
Definition at line 50 of file space.cpp.
References BUTTONSIZE, INACTIVE, letter, on_clicked(), and state.
Referenced by Space().
{
    connect(this, SIGNAL(clicked()),
            this, SLOT(on_clicked()));
    this->letter = NULL;
    this->setMinimumHeight(BUTTONSIZE);
    this->setMinimumWidth(BUTTONSIZE);
    this->setMaximumHeight(BUTTONSIZE);
    this->setMaximumWidth(BUTTONSIZE);
    this->setContentsMargins(0,0,0,0);
    this->state = INACTIVE;
    return this;
}
Friends And Related Function Documentation
friend class AIPlayer [friend]
Definition at line 77 of file space.h.
ostream& operator<< (ostream & os, const Space & space) [friend]
operator << Overloads the << operator for debugging information
Parameters
os The output stream
space The space object
Returns
The modified output stream
Definition at line 373 of file space.cpp.
                                                     {
    os << "[";
    if (space.letter == NULL){
        if (space.letterMultiplier != 1){
            os << space.letterMultiplier << 'L';
        }
        else if (space.wordMultiplier != 1){
            os << space.wordMultiplier << 'W';
        }
        else if (space.startSpace){
            os << "**";
        }
        else {
            os << " ";
        }
    }
    else {
        os << " " << space.letter->asQCharPtr()->toLatin1();
    }
    os << "]";
    return os;
}
Member Data Documentation
QString Space::color [private]
The default color of the Space
Definition at line 37 of file space.h.
Referenced by clear(), getColor(), setInactive(), and Space().
QString Space::label [private]
The label shown to the user
Definition at line 36 of file space.h.
Referenced by clear(), and Space().
Letter* Space::letter [private]
The Letter, if it exists
Definition at line 32 of file space.h.
Referenced by AIPlayer::_assist_ai_search(), clear(), getLetter(), getValue(), isBlank(), on_clicked(), operator<<(), setLetter(), setupDefaults(), Space(), and ~Space().
int Space::letterMultiplier [private]
The letter multiplier for the space
Definition at line 33 of file space.h.
Referenced by getLetterMultiplier(), getValue(), operator<<(), and Space().
bool Space::startSpace [private]
Flag whether this is the space in the very center of the board
Definition at line 35 of file space.h.
Referenced by isStartSpace(), operator<<(), setStartSpace(), and Space().
int Space::state [private]
The state of the space
Definition at line 40 of file space.h.
Referenced by clear(), isActive(), isInactive(), isNew(), isOnBoard(), isPlaced(), on_clicked(), setActive(), setInactive(), setLetter(), setNew(), setOnBoard(), setPlaced(), and setupDefaults().
int Space::wordMultiplier [private]
The word multiplier for the space
Definition at line 34 of file space.h.
Referenced by getWordMultiplier(), operator<<(), and Space().
int Space::x [private]
The x position on the board or in the rack
Definition at line 38 of file space.h.
Referenced by getX(), on_clicked(), and Space().
int Space::y [private]
The y position on the board (or -1 if in the rack
Definition at line 39 of file space.h.
Referenced by getY(), on_clicked(), and Space().
The documentation for this class was generated from the following files:
Scrabble/space.h
Scrabble/space.cpp