Board Class Reference
The Board class Singleton that represents a playing board.
#include <board.h>
Public Slots
void on_cancelButton_clicked ()
Board::on_cancelButton_clicked Cancels a play. Removes all letters from the board and resets the rack.
void on_passButton_clicked ()
Board::on_passButton_clicked Passes a players turn.
void on_playButton_clicked ()
Board::on_playButton_clicked Commits a play to the board if valid, or removes all pieces if not.
Signals
void boardClicked (int, int)
void invalidMove ()
Public Member Functions
~Board ()
Board::~Board Destructor.
Board * reset ()
Board::reset Resets the board by clearing out all the spaces.
Board * setGame (Game *)
Board::setGame Setter for game.
Game * getGame ()
Board::getGame Gets a game.
Board * setup ()
Board::setup Sets up the board.
Board * inactivateOtherSpaces (int, int)
Board::inactivateOtherSpaces Inactivates other spaces on the board.
int score (Play *)
Board::score Scores a board.
void setSpace (int, int, Letter *)
setSpace Setter for a space
QString getColor (int, int)
Board::getColor Gets the color of the space.
Board * moveLetterToBoard (int i, int x, int y)
Board::moveLetterToBoard Moves a letter to the board.
Static Public Member Functions
static Board * getBoard ()
Board::getBoard Gets the board or creates a new one.
Public Attributes
Space * spaces [BOARDSIZE][BOARDSIZE]
Private Member Functions
Board ()
Board::Board Constructor.
Board * setupSpecialSpaces ()
Board::setupSpecialSpaces Sets up special spaces on the board.
Board * setup3W ()
Board::setup3W Sets up spaces with 3 * word multiplier.
Board * setup2W ()
Board::setup2W Sets up spaces with 2 * word multiplier.
Board * setup3L ()
Board::setup3L Sets up spaces with 3 * letter multipler.
Board * setup2L ()
Board::setup2L Sets up spaces with 2 * letter multiplier.
Board * setupStart ()
Board::setupStart Sets up the start space.
Board * setupPlainSpaces ()
Board::setupPlainSpaces Sets up the rest of the board, should be called only after all the special spaces are set up.
Board * connectSpaces ()
bool validate ()
Board::validate Validates a board.
bool startCovered ()
Board::startCovered Evaluates whether the start space has been played. This should only fail on the first play.
bool hasNew ()
Board::hasNew Decides whether there is a new letter on the board.
bool sameRowOrColumn ()
Board::sameRowOrColumn Validates whether all of the new letters are in the same row or column.
bool areValidWords ()
Board::areValidWords Validates all words on the board to make sure they are valid.
bool noRowBlanks (int, int)
Board::noRowBlanks Searches in a row to make sure there are no spaces between letters.
bool noColumnBlanks (int, int)
Board::noColumnBlanks Searches in a column to make sure there are no spaces between letters.
bool mustTouchRow (int, int)
Board::mustTouchRow Evaluates whether a word touches a word currently on the board. Looks in the horiontal direction.
bool mustTouchColumn (int, int)
Board::mustTouchColumn Evaluates whether a word touches a word currently on the board. Looks in the horiontal direction.
bool isTouchingOnBoard (int, int)
Board::isTouchingOnBoard Evaluates whether a space is adjacent to a space that has a permanent letter affixed to it.
bool validateWordHorizontal (int, int)
Board::validateWordHorizontal Validates a word against the dictionary in a horizontal direction.
bool validateWordVertical (int, int)
Board::validateWordVertical Validates a word against the dictionary in a vertical direction.
int scoreVertical ()
Board::scoreVertical Scores all vertical words.
int scoreHorizontal ()
Board::scoreHorizontal Scores all horizontal words.
int scoreHorizontalWord (int row, int column)
Board::scoreHorizontalWord Score a single horizontal word.
int scoreVerticalWord (int row, int column)
Board::scoreVerticalWord Scores a single vertical word.
Private Attributes
Game * game
bool active
bool firstPlayed
Static Private Attributes
static Board * board = NULL
static bool isSet = false
Friends
class AIPlayer
ostream & operator<< (ostream &os, const Board &board)
operator << Overloading the << operator for debugging information
Detailed Description
The Board class Singleton that represents a playing board.
Definition at line 26 of file board.h.
Constructor & Destructor Documentation
Board::Board () [private]
Board::Board Constructor.
Definition at line 15 of file board.cpp.
References active, BOARDSIZE, firstPlayed, game, setup(), and spaces.
Referenced by getBoard().
{
    this->active = false;
    this->firstPlayed = false;
    this->game = NULL;
    for (int i = 0; i < BOARDSIZE; i++){
        for (int j = 0; j < BOARDSIZE; j++){
            spaces[i][j] = NULL;
        }
    }
    setup();
}
Board::~Board ()
Board::~Board Destructor.
Definition at line 47 of file board.cpp.
References BOARDSIZE, Rack::deleteLetter(), Rack::getRack(), and spaces.
{
    for (int i = 0; i < BOARDSIZE; i++){
        for (int j = 0; j < BOARDSIZE; j++){
            if (spaces[i][j] != NULL) {
                Rack::getRack()->deleteLetter(spaces[i][j]->getLetter());
                delete(spaces[i][j]);
            }
        }
    }
}
Member Function Documentation
bool Board::areValidWords () [private]
Board::areValidWords Validates all words on the board to make sure they are valid.
Returns
true if all are valid, false otherwise
Definition at line 321 of file board.cpp.
References BOARDSIZE, spaces, validateWordHorizontal(), and validateWordVertical().
Referenced by validate().
{
    for (int row = 0; row < BOARDSIZE; row++){
        for (int column = 0; column < BOARDSIZE; column++){
            if (!spaces[row][column]->isBlank() && (row == 0 || spaces[row - 1][column]->
      isBlank())) {
                if (!validateWordVertical(row, column)){
                    return false;
                }
            }
            if (!spaces[row][column]->isBlank() && (column == 0 ||
      spaces[row][column - 1]->isBlank())) {
                if (!validateWordHorizontal(row, column)){
                    return false;
                }
            }
        }
    }
    return true;
}
void Board::boardClicked (int , int) [signal]
Board* Board::connectSpaces () [private]
Board * Board::getBoard () [static]
Board::getBoard Gets the board or creates a new one.
Returns
A pointer to the board
Definition at line 33 of file board.cpp.
References board, Board(), and isSet.
Referenced by AIPlayer::_touches_2(), AIPlayer::_touches_4(), Move::apply(), Dialog::createHorizontalGroupBox(), Dialog::Dialog(), Move::finalize(), moveLetterToBoard(), Game::nextTurn(), Space::on_clicked(), on_playButton_clicked(), PlayerLabel::on_playerChanged(), operator<<(), AIPlayer::play(), Move::unapply(), and Play::validate().
{
    if (isSet){
        return board;
    }
    isSet = true;
    board = new Board();
    return board;
}
QString Board::getColor (int x, int y)
Board::getColor Gets the color of the space.
Parameters
x The x position of the space
y The y position of the space
Returns
A QString representing the color
Definition at line 280 of file board.cpp.
References Space::getColor(), and spaces.
{
    return this->spaces[x][y]->getColor();
}
Game * Board::getGame ()
Board::getGame Gets a game.
Returns
A pointer to the game
Definition at line 102 of file board.cpp.
References game.
Referenced by moveLetterToBoard(), Space::on_clicked(), and on_playButton_clicked().
{
    return game;
}
bool Board::hasNew () [private]
Board::hasNew Decides whether there is a new letter on the board.
Returns
true if there is a new letter, false otherwise
Definition at line 399 of file board.cpp.
References BOARDSIZE, and spaces.
Referenced by validate().
{
    for(int i = 0; i < BOARDSIZE; i++){
        for(int j = 0; j < BOARDSIZE; j++) {
            if (spaces[i][j]->isNew()){
                return true;
            }
        }
    }
    return false;
}
Board * Board::inactivateOtherSpaces (int x, int y)
Board::inactivateOtherSpaces Inactivates other spaces on the board.
Parameters
x The x position
y The y position
Returns
this
Definition at line 291 of file board.cpp.
References BOARDSIZE, Space::setInactive(), and spaces.
{
    for (int i = 0; i < BOARDSIZE; i++){
        for (int j = 0; j < BOARDSIZE; j++){
            if (!(x == i && y == j)){
                spaces[i][j]->setInactive();
            }
        }
    }
    return this;
}
void Board::invalidMove () [signal]
Referenced by on_playButton_clicked().
bool Board::isTouchingOnBoard (int row, int column) [private]
Board::isTouchingOnBoard Evaluates whether a space is adjacent to a space that has a permanent letter affixed to it.
Parameters
row The row of the space
column The column of the space
Returns
True if adjacent, false otherwise
Definition at line 575 of file board.cpp.
References BOARDSIZE, and spaces.
Referenced by mustTouchColumn(), mustTouchRow(), and sameRowOrColumn().
{
    if ((row > 0) && spaces[row - 1][column]->isOnBoard()){
        return true;
    }
    if ((column > 0) && spaces[row][column - 1]->isOnBoard()){
        return true;
    }
    if ((row < BOARDSIZE - 1) && spaces[row + 1][column]->isOnBoard()){
        return true;
    }
    if ((column < BOARDSIZE - 1) && spaces[row][column + 1]->isOnBoard()){
        return true;
    }
    return false;
}
Board * Board::moveLetterToBoard (int i, int x, int y)
Board::moveLetterToBoard Moves a letter to the board.
Parameters
i The position in the rack
x The x position on the board
y The y position on the board
Returns
this
Definition at line 599 of file board.cpp.
References Play::addMove(), Move::apply(), Game::currentPlay(), Game::currentPlayer(), game, getBoard(), getGame(), and Rack::getRack().
Referenced by Space::on_clicked(), and AIPlayer::play().
{
    Move *move = new Move(Board::getBoard()->getGame()->currentPlayer(),
                          Rack::getRack()->getSpace(i)->getLetter(),
                          i, x, y);
    move->apply();
    Game *game = Board::getBoard()->getGame();
    game->currentPlay()->addMove(game->currentPlayer(), move);
    return this;
}
bool Board::mustTouchColumn (int firstRow, int firstColumn) [private]
Board::mustTouchColumn Evaluates whether a word touches a word currently on the board. Looks in the horiontal direction.
Parameters
firstRow The row of the first letter
firstColumn The column of the first letter
Returns
true if it touches, false if not
Definition at line 552 of file board.cpp.
References BOARDSIZE, isTouchingOnBoard(), and spaces.
Referenced by sameRowOrColumn().
{
    for (int row = firstRow; row < BOARDSIZE; row++){
        if (spaces[row][firstColumn]->isBlank()){
            return false;
        }
        else if (row == 7 && firstColumn == 7){
            return true;
        }
        else if (isTouchingOnBoard(row, firstColumn)){
            return true;
        }
    }
    return false;
}
bool Board::mustTouchRow (int firstRow, int firstColumn) [private]
Board::mustTouchRow Evaluates whether a word touches a word currently on the board. Looks in the horiontal direction.
Parameters
firstRow The row of the first letter.
firstColumn The column of the first letter.
Returns
true if it touches, false if not
Definition at line 529 of file board.cpp.
References BOARDSIZE, isTouchingOnBoard(), and spaces.
Referenced by sameRowOrColumn().
{
    for (int column = firstColumn; column < BOARDSIZE; column++){
        if (spaces[firstRow][column]->isBlank()){
            return false;
        }
        else if (firstRow == 7 && column == 7){
            return true;
        }
        else if (isTouchingOnBoard(firstRow, column)){
            return true;
        }
    }
    return false;
}
bool Board::noColumnBlanks (int firstRow, int firstColumn) [private]
Board::noColumnBlanks Searches in a column to make sure there are no spaces between letters.
Parameters
firstRow The row of the first letter.
firstColumn The column of the first letter.
Returns
true if no spaces found, false otherwise
Definition at line 508 of file board.cpp.
References BOARDSIZE, and spaces.
Referenced by sameRowOrColumn().
{
    bool spaceSeen = false;
    for (int row = firstRow + 1; row < BOARDSIZE; row++){
        if (!spaceSeen && spaces[row][firstColumn]->isBlank()){
             spaceSeen = true;
        }
        if (spaceSeen && spaces[row][firstColumn]->isNew()){
            return false;
        }
    }
    return true;
}
bool Board::noRowBlanks (int firstRow, int firstColumn) [private]
Board::noRowBlanks Searches in a row to make sure there are no spaces between letters.
Parameters
firstRow The row of the first letter
firstColumn The column of the first letter
Returns
true if no spaces found, false otherwise
Definition at line 487 of file board.cpp.
References BOARDSIZE, and spaces.
Referenced by sameRowOrColumn().
{
    bool spaceSeen = false;
    for (int column = firstColumn + 1; column < BOARDSIZE; column++){
        if (!spaceSeen && spaces[firstRow][column]->isBlank()){
             spaceSeen = true;
        }
        if (spaceSeen && spaces[firstRow][column]->isNew()){
            return false;
        }
    }
    return true;
}
void Board::on_cancelButton_clicked () [slot]
Board::on_cancelButton_clicked Cancels a play. Removes all letters from the board and resets the rack.
Definition at line 761 of file board.cpp.
References BOARDSIZE, Space::clear(), Play::clearMoves(), Game::currentPlay(), game, and spaces.
Referenced by on_passButton_clicked(), and on_playButton_clicked().
{
    for (int i = 0; i < BOARDSIZE; i++){
        for (int j = 0; j < BOARDSIZE; j++) {
            if (spaces[i][j]->isNew() || spaces[i][j]->isActive()) {
                spaces[i][j]->clear();
            }
        }
    }
    game->currentPlay()->clearMoves();
}
void Board::on_passButton_clicked () [slot]
Board::on_passButton_clicked Passes a players turn.
Definition at line 776 of file board.cpp.
References game, Game::nextTurn(), and on_cancelButton_clicked().
{
    on_cancelButton_clicked();
    game->nextTurn();
}
void Board::on_playButton_clicked () [slot]
Board::on_playButton_clicked Commits a play to the board if valid, or removes all pieces if not.
Definition at line 786 of file board.cpp.
References game, getBoard(), getGame(), invalidMove(), Game::nextTurn(), on_cancelButton_clicked(), and validate().
{
    if (validate()) {
        Game *game = Board::getBoard()->getGame();
        game->nextTurn();
    }
    else {
        on_cancelButton_clicked();
        emit(invalidMove());
    }
}
Board * Board::reset ()
Board::reset Resets the board by clearing out all the spaces.
Returns
this
Definition at line 63 of file board.cpp.
References active, BOARDSIZE, Space::clear(), and spaces.
Referenced by Dialog::on_newGame_selected().
{
    for (int i = 0; i < BOARDSIZE; i++){
        for (int j = 0; j < BOARDSIZE; j++){
            if (spaces[i][j] != NULL) {
                spaces[i][j]->clear();
            }
        }
    }
    this->active = false;
    return this;
}
bool Board::sameRowOrColumn () [private]
Board::sameRowOrColumn Validates whether all of the new letters are in the same row or column.
Returns
true if they are, false if not
Definition at line 416 of file board.cpp.
References BOARDSIZE, isTouchingOnBoard(), mustTouchColumn(), mustTouchRow(), noColumnBlanks(), noRowBlanks(), and spaces.
Referenced by validate().
{
    bool found = false;
    bool secondFound = false;
    bool row = false;
    bool column = false;
    int firstRow = -1;
    int firstColumn = -1;
    // Figure out whether the pieces are in a row or column
    // We need two new spaces to do this.
    for(int i = 0; i < BOARDSIZE; i++){
        for(int j = 0; j < BOARDSIZE; j++) {
            // Finds the first space on the board
            // It doesn't really matter which we choose as the first space
            // As long it is the first we encounter
            if (!found && spaces[i][j]->isNew()){
                found = true;
                firstRow = i;
                firstColumn = j;
            }
            // Finds the second space and figures out whether it is in
            // the same row or column as the first
            // If not it returns false
            else if (!secondFound && spaces[i][j]->isNew()){
                secondFound = true;
                if (firstRow == i) {
                    row = true;
                }
                else if (firstColumn == j){
                    column = true;
                }
                else {
                    return false;
                }
            }
            // Makes sure all other spaces are either
            // in the same row or same column
            else if (spaces[i][j]->isNew()){
                if ((row && firstRow != i) ||
                        (column && firstColumn != j)){
                    return false;
                }
            }
        }
    }
    // Checks to make sure it meets other criteria
    if (row) {
        return noRowBlanks(firstRow, firstColumn)
                && mustTouchRow(firstRow, firstColumn);
    }
    else if (column){
        return noColumnBlanks(firstRow, firstColumn)
                && mustTouchColumn(firstRow, firstColumn);
    }
    else { // there is just one new letter on the board
        return isTouchingOnBoard(firstRow, firstColumn);
    }
}
int Board::score (Play * play)
Board::score Scores a board.
Parameters
play The current play
Returns
this
Definition at line 616 of file board.cpp.
References scoreHorizontal(), scoreVertical(), and Play::size().
Referenced by scoreHorizontal(), scoreHorizontalWord(), scoreVertical(), and scoreVerticalWord().
{
    int score = 0;
    // If the play uses all 7 letters a bonus of 50 points is applied
    if(play->size() == 7){
        score += 50;
    }
    score += scoreHorizontal();
    score += scoreVertical();
    cout << "The score is " << score << "."<< endl;
    return score;
}
int Board::scoreHorizontal () [private]
Board::scoreHorizontal Scores all horizontal words.
Returns
The score
Definition at line 634 of file board.cpp.
References BOARDSIZE, score(), scoreHorizontalWord(), and spaces.
Referenced by score().
{
    int score = 0;
    for (int row = 0; row < BOARDSIZE; row++){
        for (int column = 0; column < BOARDSIZE - 1; column++){
                                                   // A horizontal word must be at least 2 letters
                                                   // So we don't have to check the last row
            if ((column == 0 || spaces[row][column - 1]->isBlank()) &&
                    !spaces[row][column]->isBlank()){
                score += scoreHorizontalWord(row, column);
            }
        }
    }
    return score;
}
int Board::scoreHorizontalWord (int firstRow, int firstColumn) [private]
Board::scoreHorizontalWord Score a single horizontal word.
Parameters
firstRow The x position of the first letter
firstColumn The y position of the first letter
Returns
The score
Definition at line 675 of file board.cpp.
References BOARDSIZE, Space::getLetter(), Space::getLetterMultiplier(), Letter::getValue(), Space::getWordMultiplier(), Space::isBlank(), Space::isNew(), score(), and spaces.
Referenced by scoreHorizontal().
{
    int score = 0;
    int length = 0;
    int isNew = false;
    int wordMultiplier = 1;
    int column = firstColumn;
    // figures out the length of the word
    Space* space = spaces[firstRow][column];
    while(column < BOARDSIZE &&
          (space = spaces[firstRow][column]) &&
          !space->isBlank()){
        length++;
        if (space->isNew()){
            isNew = true;
        }
        column++;
    }
    // calculates the score for the word
    if (length > 1 && isNew){
        for(int i = 0; i < length; i++){
            space = spaces[firstRow][firstColumn + i];
            if (space->isNew()){
                score += space->getLetter()->getValue() * space->
      getLetterMultiplier();
                wordMultiplier *= space->getWordMultiplier();
            }
            else {
                score += space->getLetter()->getValue();
            }
        }
    }
    score = score * wordMultiplier;
    return score;
}
int Board::scoreVertical () [private]
Board::scoreVertical Scores all vertical words.
Returns
The score
Definition at line 654 of file board.cpp.
References BOARDSIZE, score(), scoreVerticalWord(), and spaces.
Referenced by score().
{
    int score = 0;
    for (int row = 0; row < BOARDSIZE - 1; row++){ // A vertical word must be at least 2 letters
                                                   // So we don't have to check the last row
        for (int column = 0; column < BOARDSIZE; column++){
            if ((row == 0 || spaces[row -1][column]->isBlank()) &&
                    !spaces[row][column]->isBlank()){
                score += scoreVerticalWord(row, column);
            }
        }
    }
    return score;
}
int Board::scoreVerticalWord (int firstRow, int firstColumn) [private]
Board::scoreVerticalWord Scores a single vertical word.
Parameters
firstRow The x position of the first new letter
firstColumn The y position of the first new letter
Returns
The value of the word
Definition at line 719 of file board.cpp.
References BOARDSIZE, Space::getLetter(), Space::getLetterMultiplier(), Letter::getValue(), Space::getWordMultiplier(), Space::isBlank(), Space::isNew(), score(), and spaces.
Referenced by scoreVertical().
{
    int score = 0;
    int length = 0;
    int isNew = false;
    int wordMultiplier = 1;
    int row = firstRow;
    // figures out the length of the word
    Space* space = spaces[row][firstColumn];
    while(row < BOARDSIZE &&
          (space = spaces[row][firstColumn]) &&
          !space->isBlank()){
        length++;
        if (space->isNew()){
            isNew = true;
        }
        row++;
    }
    // figures out the vaue of the word
    if (length > 1 && isNew){
        for(int i = 0; i < length; i++){
            space = spaces[firstRow + i][firstColumn];
            if (space->isNew()){ // Mulltipliers only apply for new letters
                score += space->getLetter()->getValue() * space->
      getLetterMultiplier();
                wordMultiplier *= space->getWordMultiplier();
            }
            else {
                score += space->getLetter()->getValue();
            }
        }
    }
    score = score * wordMultiplier;
    return score;
}
Board * Board::setGame (Game * game)
Board::setGame Setter for game.
Parameters
game The game
Returns
this
Definition at line 92 of file board.cpp.
References game.
Referenced by Dialog::setupGame().
{
    this->game = game;
    return this;
}
void Board::setSpace (int x, int y, Letter * l)
setSpace Setter for a space
Parameters
x The x position to set
y The y position to set
l The pointer to the letter which we will insert in the spot
Definition at line 266 of file board.cpp.
References BOARDSIZE, Space::setLetter(), and spaces.
{
    assert(x >=0 && x < BOARDSIZE);
    assert(y >=0 && y < BOARDSIZE);
    spaces[x][y]->setLetter(l);
}
Board * Board::setup ()
Board::setup Sets up the board.
Returns
this
Definition at line 80 of file board.cpp.
References setupPlainSpaces(), and setupSpecialSpaces().
Referenced by Board().
{
    setupSpecialSpaces();
    setupPlainSpaces();
    return this;
}
Board * Board::setup2L () [private]
Board::setup2L Sets up spaces with 2 * letter multiplier.
Returns
this
Definition at line 210 of file board.cpp.
References DOUBLELETTERCOLOR, and spaces.
Referenced by setupSpecialSpaces().
{
    int lm = 2, wm = 1;
    QString label = "2l", color = DOUBLELETTERCOLOR;
    spaces[0][3] = new Space(0, 3, lm, wm, label, color);
    spaces[0][11] = new Space(0, 11, lm, wm, label, color);
    spaces[2][6] = new Space(2, 6, lm, wm, label, color);
    spaces[2][8] = new Space(2, 8, lm, wm, label, color);
    spaces[3][0] = new Space(3, 0, lm, wm, label, color);
    spaces[3][7] = new Space(3, 7, lm, wm, label, color);
    spaces[3][14] = new Space(3, 14, lm, wm, label, color);
    spaces[6][2] = new Space(6, 2, lm, wm, label, color);
    spaces[6][6] = new Space(6, 6, lm, wm, label, color);
    spaces[6][8] = new Space(6, 8, lm, wm, label, color);
    spaces[6][12] = new Space(6, 12, lm, wm, label, color);
    spaces[7][3] = new Space(7, 3, lm, wm, label, color);
    spaces[7][11] = new Space(7, 11, lm, wm, label, color);
    spaces[8][2] = new Space(8, 2, lm, wm, label, color);
    spaces[8][6] = new Space(8, 6, lm, wm, label, color);
    spaces[8][8] = new Space(8, 8, lm, wm, label, color);
    spaces[8][12] = new Space(8, 12, lm, wm, label, color);
    spaces[11][0] = new Space(11, 0, lm, wm, label, color);
    spaces[11][7] = new Space(11, 7, lm, wm, label, color);
    spaces[11][14] = new Space(11, 14, lm, wm, label, color);
    spaces[12][6] = new Space(12, 6, lm, wm, label, color);
    spaces[12][8] = new Space(12, 8, lm, wm, label, color);
    spaces[14][3] = new Space(14, 3, lm, wm, label, color);
    spaces[14][11] = new Space(14, 11, lm, wm, label, color);
    return this;
}
Board * Board::setup2W () [private]
Board::setup2W Sets up spaces with 2 * word multiplier.
Returns
this
Definition at line 158 of file board.cpp.
References DOUBLEWORDCOLOR, and spaces.
Referenced by setupSpecialSpaces().
{
    int lm = 1, wm = 2;
    QString label = "2w", color = DOUBLEWORDCOLOR;
    spaces[1][1] = new Space(1, 1, lm, wm, label, color);
    spaces[2][2] = new Space(2, 2, lm, wm, label, color);
    spaces[3][3] = new Space(3, 3, lm, wm, label, color);
    spaces[4][4] = new Space(4, 4, lm, wm, label, color);
    spaces[1][13] = new Space(1, 13, lm, wm, label, color);
    spaces[2][12] = new Space(2, 12, lm, wm, label, color);
    spaces[3][11] = new Space(3, 11, lm, wm, label, color);
    spaces[4][10] = new Space(4, 10, lm, wm, label, color);
    spaces[10][4] = new Space(10, 4, lm, wm, label, color);
    spaces[11][3] = new Space(11, 3, lm, wm, label, color);
    spaces[12][2] = new Space(12, 2, lm, wm, label, color);
    spaces[13][1] = new Space(13, 1, lm, wm, label, color);
    spaces[10][10] = new Space(10, 10, lm, wm, label, color);
    spaces[11][11] = new Space(11, 11, lm, wm, label, color);
    spaces[12][12] = new Space(12, 12, lm, wm, label, color);
    spaces[13][13] = new Space(13, 13, lm, wm, label, color);
    return this;
}
Board * Board::setup3L () [private]
Board::setup3L Sets up spaces with 3 * letter multipler.
Returns
this
Definition at line 186 of file board.cpp.
References spaces, and TRIPLELETTERCOLOR.
Referenced by setupSpecialSpaces().
{
    int lm = 3, wm = 1;
    QString label = "3l", color = TRIPLELETTERCOLOR;
    spaces[1][5] = new Space(1, 5, lm, wm, label, color);
    spaces[1][9] = new Space(1, 9, lm, wm, label, color);
    spaces[5][1] = new Space(5, 1, lm, wm, label, color);
    spaces[5][5] = new Space(5, 5, lm, wm, label, color);
    spaces[5][9] = new Space(5, 9, lm, wm, label, color);
    spaces[5][13] = new Space(5, 13, lm, wm, label, color);
    spaces[9][1] = new Space(9, 1, lm, wm, label, color);
    spaces[9][5] = new Space(9, 5, lm, wm, label, color);
    spaces[9][9] = new Space(9, 9, lm, wm, label, color);
    spaces[9][13] = new Space(9, 13, lm, wm, label, color);
    spaces[13][5] = new Space(13, 5, lm, wm, label, color);
    spaces[13][9] = new Space(13, 9, lm, wm, label, color);
    return this;
}
Board * Board::setup3W () [private]
Board::setup3W Sets up spaces with 3 * word multiplier.
Returns
this
Definition at line 138 of file board.cpp.
References spaces, and TRIPLEWORDCOLOR.
Referenced by setupSpecialSpaces().
{
    int lm = 1, wm = 3;
    QString label = "3w", color = TRIPLEWORDCOLOR;
    spaces[0][0] = new Space(0, 0, lm, wm, label, color);
    spaces[0][7] = new Space(0, 7, lm, wm, label, color);
    spaces[0][14] = new Space(0, 14, lm, wm, label, color);
    spaces[7][0] = new Space(7, 0, lm, wm, label, color);
    spaces[7][14] = new Space(7, 14, lm, wm, label, color);
    spaces[14][0] = new Space(14, 0, lm, wm, label, color);
    spaces[14][7] = new Space(14, 7, lm, wm, label, color);
    spaces[14][14] = new Space(14, 14, lm, wm, label, color);
    return this;
}
Board * Board::setupPlainSpaces () [private]
Board::setupPlainSpaces Sets up the rest of the board, should be called only after all the special spaces are set up.
Returns
this
Definition at line 247 of file board.cpp.
References BOARDSIZE, and spaces.
Referenced by setup().
{
    for (int i = 0; i < BOARDSIZE; i++){
        for (int j = 0; j < BOARDSIZE; j++){
            if (spaces[i][j] == NULL){
                spaces[i][j] = new Space(i, j, 1, 1, " ", "white");
            }
        }
    }
    return this;
}
Board * Board::setupSpecialSpaces () [private]
Board::setupSpecialSpaces Sets up special spaces on the board.
Returns
this
Definition at line 111 of file board.cpp.
References setup2L(), setup2W(), setup3L(), setup3W(), and setupStart().
Referenced by setup().
{
    setup3W();
    setup2W();
    setup3L();
    setup2L();
    setupStart();
    return this;
}
Board * Board::setupStart () [private]
Board::setupStart Sets up the start space.
Returns
this
Definition at line 126 of file board.cpp.
References DOUBLEWORDCOLOR, Space::setStartSpace(), and spaces.
Referenced by setupSpecialSpaces().
{
    spaces[7][7] = new Space(7, 7, 1, 2, "*", DOUBLEWORDCOLOR);
    spaces[7][7]->setStartSpace(true);
    return this;
}
bool Board::startCovered () [private]
Board::startCovered Evaluates whether the start space has been played. This should only fail on the first play.
Returns
true if it is covered, false otherwise
Definition at line 389 of file board.cpp.
References firstPlayed, Space::getLetter(), and spaces.
Referenced by AIPlayer::play(), and validate().
{
    return firstPlayed || (spaces[7][7]->getLetter() != NULL);
}
bool Board::validate () [private]
Board::validate Validates a board.
Returns
true if valid, false otherwise
The start space should be covered There should be at least one new letter on the board The letters should all be in one row or column
Definition at line 307 of file board.cpp.
References areValidWords(), hasNew(), sameRowOrColumn(), and startCovered().
Referenced by on_playButton_clicked(), and AIPlayer::play().
{
    bool isValidPosition = startCovered() && hasNew() &&
      sameRowOrColumn();
    return isValidPosition && areValidWords();
}
bool Board::validateWordHorizontal (int firstRow, int firstColumn) [private]
Board::validateWordHorizontal Validates a word against the dictionary in a horizontal direction.
Parameters
firstRow The first row of the word
firstColumn The first column of the word
Returns
true if a valid word, false otherwise
Definition at line 346 of file board.cpp.
References Letter::asQCharPtr(), BOARDSIZE, Game::dictionary, game, Space::getLetter(), Dictionary::isWord(), and spaces.
Referenced by areValidWords().
{
    QString word = "";
    int column = firstColumn;
    while (column < BOARDSIZE && !spaces[firstRow][column]->isBlank()){
        word = word + spaces[firstRow][column]->getLetter()->
      asQCharPtr()->toLatin1();
        column++;
    }
    if (column > (firstColumn + 1) && !game->dictionary->isWord(word)){
        cout << word.toStdString() << " is not a word." << endl;
        return false;
    }
    return true;
}
bool Board::validateWordVertical (int firstRow, int firstColumn) [private]
Board::validateWordVertical Validates a word against the dictionary in a vertical direction.
Parameters
firstRow The first row of the word
firstColumn The first column of the word
Returns
true if valid, false otherwise
Definition at line 367 of file board.cpp.
References Letter::asQCharPtr(), BOARDSIZE, Game::dictionary, game, Space::getLetter(), Dictionary::isWord(), and spaces.
Referenced by areValidWords().
{
    QString word = "";
    word = "";
    int row = firstRow;
    while (row < BOARDSIZE && !spaces[row][firstColumn]->isBlank()){
        word = word + spaces[row][firstColumn]->getLetter()->
      asQCharPtr()->toLatin1();
        row++;
    }
    if (row > (firstRow + 1) && !game->dictionary->isWord(word)){
        cout << word.toStdString() << " is not a word." << endl;
        return false;
    }
    return true;
}
Friends And Related Function Documentation
friend class AIPlayer [friend]
Definition at line 80 of file board.h.
ostream& operator<< (ostream & os, const Board & board) [friend]
operator << Overloading the << operator for debugging information
Parameters
os The output stream
board The board to be output
Returns
The modified output stream
Definition at line 804 of file board.cpp.
{
    for(int i = 0; i < BOARDSIZE; i++) {
        cout << "{" << setw(2) << i << "}";
        for(int j = 0; j < BOARDSIZE; j++) {
            os << *(board.spaces[i][j]);
        }
        os << endl;
    }
    cout << "{XX}{0 }{1 }{2 }{3 }{4 }{5 }{6 }{7 }{8 }{9 }{10}{11}{12}{13}{14}";
    return os;
}
Member Data Documentation
bool Board::active [private]
Indicator that the board has an active space
Definition at line 34 of file board.h.
Referenced by Board(), and reset().
Board * Board::board = NULL [static], [private]
The playing board
Definition at line 30 of file board.h.
Referenced by getBoard().
bool Board::firstPlayed [private]
Indicator that the first play has been made
Definition at line 35 of file board.h.
Referenced by Board(), and startCovered().
Game* Board::game [private]
The game
Definition at line 33 of file board.h.
Referenced by Board(), getGame(), moveLetterToBoard(), on_cancelButton_clicked(), on_passButton_clicked(), on_playButton_clicked(), setGame(), validateWordHorizontal(), and validateWordVertical().
bool Board::isSet = false [static], [private]
True if the board has been set
Definition at line 31 of file board.h.
Referenced by getBoard().
Space* Board::spaces[BOARDSIZE][BOARDSIZE]
Container for spaces
Definition at line 66 of file board.h.
Referenced by AIPlayer::_touches_2(), Move::apply(), areValidWords(), Board(), Dialog::createGridGroupBox(), Move::finalize(), getColor(), hasNew(), inactivateOtherSpaces(), isTouchingOnBoard(), mustTouchColumn(), mustTouchRow(), noColumnBlanks(), noRowBlanks(), on_cancelButton_clicked(), operator<<(), AIPlayer::play(), reset(), sameRowOrColumn(), scoreHorizontal(), scoreHorizontalWord(), scoreVertical(), scoreVerticalWord(), setSpace(), setup2L(), setup2W(), setup3L(), setup3W(), setupPlainSpaces(), setupStart(), startCovered(), Move::unapply(), Play::validate(), Play::validate_down(), Play::validate_right(), validateWordHorizontal(), validateWordVertical(), and ~Board().
The documentation for this class was generated from the following files:
Scrabble/board.h
Scrabble/board.cpp