TrieNode Class Reference
The TrieNode class A node in a Trie.
#include <trienode.h>
Public Member Functions
TrieNode ()
TrieNode::TrieNode Default constructor.
TrieNode (QChar c, bool isWord)
TrieNode::TrieNode Overloaded constructor for quicker building.
~TrieNode ()
TrieNode::~TrieNode Default Destructor.
void setWordMarker ()
TrieNode::setWordMarker Set that this TrieNode marks a complete word.
void appendChild (TrieNode *child)
TrieNode::appendChild Add a child to the children defining vector<TrieNode*> of this TrieNode.
QChar content ()
TrieNode::content Getter for the character that defines this TrieNode.
bool isWord ()
TrieNode::isWord Does this TrieNode mark a complete word?
vector< TrieNode * > children ()
TrieNode::appendChild Returns the vector encompassing this TrieNode's children.
TrieNode * findChild (QChar c)
TrieNode::findChild Finds the child that contains the alphabetic character we seek.
Private Attributes
QChar character
bool wordmarker
vector< TrieNode * > triechildren
Friends
class Trie
Detailed Description
The TrieNode class A node in a Trie.
Definition at line 12 of file trienode.h.
Constructor & Destructor Documentation
TrieNode::TrieNode ()
TrieNode::TrieNode Default constructor.
Definition at line 6 of file trienode.cpp.
References character, triechildren, and wordmarker.
                   {
    triechildren.clear();
    character = ' ';
    wordmarker = false;
}
TrieNode::TrieNode (QChar c, bool isWord)
TrieNode::TrieNode Overloaded constructor for quicker building.
Parameters
c What is the character this node defines?
isWord Does this indicate the final letter of a word?
Definition at line 17 of file trienode.cpp.
References character, isWord(), triechildren, and wordmarker.
                                       {
    triechildren.clear();
    character = c;
    wordmarker = isWord;
}
TrieNode::~TrieNode ()
TrieNode::~TrieNode Default Destructor.
Definition at line 26 of file trienode.cpp.
References triechildren.
                    {
    while(!this->triechildren.empty()){
        delete this->triechildren.back();
        this->triechildren.pop_back();
    }
}
Member Function Documentation
void TrieNode::appendChild (TrieNode * child)
TrieNode::appendChild Add a child to the children defining vector<TrieNode*> of this TrieNode.
Parameters
child The TrieNode you wish to append to the current TrieNode's children.
Definition at line 75 of file trienode.cpp.
References triechildren.
Referenced by Trie::addWord().
                                          {
    triechildren.push_back(child);
}
vector< TrieNode * > TrieNode::children ()
TrieNode::appendChild Returns the vector encompassing this TrieNode's children.
Returns
The children for this TrieNode.
Definition at line 83 of file trienode.cpp.
References triechildren.
Referenced by Trie::_printTrie().
                                     {
    return triechildren;
}
QChar TrieNode::content ()
TrieNode::content Getter for the character that defines this TrieNode.
Returns
The character stored in this TrieNode.
Definition at line 52 of file trienode.cpp.
References character.
Referenced by Trie::_printTrie(), and findChild().
                        {
    return character;
}
TrieNode * TrieNode::findChild (QChar c)
TrieNode::findChild Finds the child that contains the alphabetic character we seek.
Returns
The pointer to the TritriechildreneNode where the alphabetic character was found.
Definition at line 37 of file trienode.cpp.
References content(), and triechildren.
Referenced by Trie::_anagramgen(), AIPlayer::_assist_ai_search(), Trie::_assist_ai_search(), Trie::addWord(), and Trie::searchWord().
{
    for (unsigned i = 0; i < triechildren.size(); i++)
    {
        TrieNode* tmp = triechildren.at(i);
        if (tmp->content() == c)
            return tmp;
    }
    return NULL;
}
bool TrieNode::isWord ()
TrieNode::isWord Does this TrieNode mark a complete word?
Returns
The boolean representation of wether this is a word or not.
Definition at line 60 of file trienode.cpp.
References wordmarker.
Referenced by Trie::_anagramgen(), AIPlayer::_assist_ai_search(), Trie::_assist_ai_search(), Trie::_printTrie(), Trie::searchWord(), and TrieNode().
                      {
    return wordmarker;
}
void TrieNode::setWordMarker ()
TrieNode::setWordMarker Set that this TrieNode marks a complete word.
Definition at line 67 of file trienode.cpp.
References wordmarker.
Referenced by Trie::addWord().
                             {
    wordmarker = true;
}
Friends And Related Function Documentation
friend class Trie [friend]
Definition at line 14 of file trienode.h.
Member Data Documentation
QChar TrieNode::character [private]
This node's defining 'character'
Definition at line 29 of file trienode.h.
Referenced by content(), and TrieNode().
vector<TrieNode*> TrieNode::triechildren [private]
Container for TrieNodes, order is not guaranteed
Definition at line 31 of file trienode.h.
Referenced by appendChild(), children(), findChild(), TrieNode(), and ~TrieNode().
bool TrieNode::wordmarker [private]
Defines if this node indicates that this node completes a word
Definition at line 30 of file trienode.h.
Referenced by isWord(), setWordMarker(), and TrieNode().
The documentation for this class was generated from the following files:
Scrabble/trienode.h
Scrabble/trienode.cpp