PlayerLabel Class Reference
The PlayerLabel class Represents the Player within the Dialog.
#include <playerlabel.h>
Public Slots
void on_playerChanged ()
PlayerLabel::on_playerChanged Handes playerChanged events.
Public Member Functions
PlayerLabel (Player *)
PlayerLabel::PlayerLabel Constructor.
PlayerLabel * setActive ()
PlayerLabel::setActive Sets the player as active.
PlayerLabel * setInactive ()
PlayerLabel::setInactive Set the player as inactive.
Private Member Functions
PlayerLabel * updateText ()
PlayerLabel::updateText Updates the text.
Private Attributes
Player * player
Detailed Description
The PlayerLabel class Represents the Player within the Dialog.
Definition at line 10 of file playerlabel.h.
Constructor & Destructor Documentation
PlayerLabel::PlayerLabel (Player * player) [explicit]
PlayerLabel::PlayerLabel Constructor.
Parameters
player
Definition at line 7 of file playerlabel.cpp.
References player.
                                       :
    QLabel()
{
    this->player = player;
}
Member Function Documentation
void PlayerLabel::on_playerChanged () [slot]
PlayerLabel::on_playerChanged Handes playerChanged events.
Definition at line 16 of file playerlabel.cpp.
References Board::getBoard(), player, setActive(), setInactive(), and updateText().
{
    if (player == Board::getBoard()->getGame()->currentPlayer()){
        updateText();
        setActive();
    }
    else {
        updateText();
        setInactive();
    }
}
PlayerLabel * PlayerLabel::setActive ()
PlayerLabel::setActive Sets the player as active.
Returns
this
Definition at line 32 of file playerlabel.cpp.
References updateText().
Referenced by Dialog::createLabelGroupBox(), and on_playerChanged().
{
    updateText();
    this->setStyleSheet("QLabel { color : red; }");
    return this;
}
PlayerLabel * PlayerLabel::setInactive ()
PlayerLabel::setInactive Set the player as inactive.
Returns
this
Definition at line 43 of file playerlabel.cpp.
References updateText().
Referenced by Dialog::createLabelGroupBox(), and on_playerChanged().
{
    updateText();
    this->setStyleSheet("QLabel { color : back; }");
    return this;
}
PlayerLabel * PlayerLabel::updateText () [private]
PlayerLabel::updateText Updates the text.
Returns
this
Definition at line 54 of file playerlabel.cpp.
References Player::getName(), Player::getScore(), and player.
Referenced by on_playerChanged(), setActive(), and setInactive().
{
    if (player != NULL) {
        setText(player->getName() + " " + QString::number(
      player->getScore()));
    }
    return this;
}
Member Data Documentation
Player* PlayerLabel::player [private]
The Player
Definition at line 19 of file playerlabel.h.
Referenced by on_playerChanged(), PlayerLabel(), and updateText().
The documentation for this class was generated from the following files:
Scrabble/playerlabel.h
Scrabble/playerlabel.cpp