Letter Class Reference
The Letter class Encapsulates a Letter (or Tile)
#include <letter.h>
Public Member Functions
Letter (QChar)
Letter::Letter Constructor.
unsigned int getValue ()
Letter::getValue Getter for value.
void setLetter (QChar)
Letter::setValue Setter for value, only for wildcards.
bool isAMatch (QChar)
Letter::isAMatch Tests if a character is a match to this letter.
bool isWildcard ()
Letter::isWildcard.
QChar * asQCharPtr ()
Letter::getLetter Getter for this letter.
Private Attributes
QChar letter
unsigned int value
bool wildcard
Friends
ostream & operator<< (ostream &os, const Letter &letter)
operator << Overloaded ostream operator
Detailed Description
The Letter class Encapsulates a Letter (or Tile)
Definition at line 11 of file letter.h.
Constructor & Destructor Documentation
Letter::Letter (QChar letter)
Letter::Letter Constructor.
Parameters
letter The letter to set
Definition at line 8 of file letter.cpp.
References value, and wildcard.
                          {
    wildcard = false;
    this->letter = letter.toLower();
    switch (this->letter.toLatin1()) {
    case('d'):
    case('g'):
        this->value = 2;
        break;
    case('b'):
    case('c'):
    case('m'):
    case('p'):
        this->value = 3;
        break;
    case('f'):
    case('h'):
    case('v'):
    case('w'):
    case('y'):
       this->value = 4;
       break;
    case('k'):
        this->value = 5;
        break;
    case('j'):
    case('x'):
        this->value = 8;
        break;
    case('q'):
    case('z'):
        this->value = 10;
        break;
    case(' '):
        this->value = 0;
        wildcard = true;
        break;
    default:
        this->value = 1;
        break;
    }
}
Member Function Documentation
QChar * Letter::asQCharPtr ()
Letter::getLetter Getter for this letter.
Returns
this
Definition at line 94 of file letter.cpp.
References letter.
Referenced by AIPlayer::_assist_ai_search(), Play::getCharArray(), Space::on_clicked(), operator<<(), Space::setLetter(), Play::validate_down(), Play::validate_right(), Board::validateWordHorizontal(), and Board::validateWordVertical().
                         {
    return &(this->letter);
}
unsigned int Letter::getValue ()
Letter::getValue Getter for value.
Returns
value
Definition at line 55 of file letter.cpp.
References value.
Referenced by Space::getValue(), Board::scoreHorizontalWord(), Board::scoreVerticalWord(), and Space::setLetter().
                             {
    return (this->value);
}
bool Letter::isAMatch (QChar c)
Letter::isAMatch Tests if a character is a match to this letter.
Parameters
c The char to compare
Returns
True if the character is a match, false otherwise
Definition at line 86 of file letter.cpp.
References letter.
Referenced by Space::on_clicked().
                            {
    return this->letter == c;
}
bool Letter::isWildcard ()
Letter::isWildcard.
Returns
Definition at line 75 of file letter.cpp.
References wildcard.
Referenced by Space::on_clicked().
{
    return wildcard;
}
void Letter::setLetter (QChar c)
Letter::setValue Setter for value, only for wildcards.
Parameters
c The value to set
Returns
this
Definition at line 64 of file letter.cpp.
References letter, and wildcard.
Referenced by Space::on_clicked().
{
    if (wildcard){
        letter = c;
    }
}
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const Letter & letter) [friend]
operator << Overloaded ostream operator
Parameters
os The ostream
letter The letter
Returns
The modified ostream
Definition at line 104 of file letter.cpp.
                                                       {
    os << letter.letter.toLatin1();
    return os;
}
Member Data Documentation
QChar Letter::letter [private]
The letter assigned to this tile
Definition at line 13 of file letter.h.
Referenced by asQCharPtr(), isAMatch(), operator<<(), and setLetter().
unsigned int Letter::value [private]
The numerical value of the tile
Definition at line 14 of file letter.h.
Referenced by getValue(), and Letter().
bool Letter::wildcard [private]
True if the tile can represent any letter
Definition at line 15 of file letter.h.
Referenced by isWildcard(), Letter(), and setLetter().
The documentation for this class was generated from the following files:
Scrabble/letter.h
Scrabble/letter.cpp